import {l,type Localized} from '../lib/learning-path';
type Unit={title:Localized;application:Localized;depth:Localized;lesson:Localized;problems:{prompt:Localized;answer:Localized}[]};
const exercise=(vi:string,en:string,va:string,ea:string)=>({prompt:l(vi,en),answer:l(va,ea)});
export const derivativesUnits:Unit[]=[
 {title:l('Brownian và biến phân toàn phương','Brownian motion and quadratic variation'),application:l('Mô phỏng cú sốc giá với đúng quy mô thời gian.','Simulate price shocks with the correct time scaling.'),depth:l('Dạy định nghĩa; dẫn xuất moment và hội tụ L² trên lưới đều. Không chứng minh sự tồn tại quá trình Brownian.','Definition taught; moments and L² convergence on uniform partitions derived. Brownian existence is assumed.'),lesson:l(String.raw`Brownian chuẩn $W_t$ có $W_0=0$, đường đi liên tục, gia số độc lập và $W_t-W_s\sim N(0,t-s)$ khi $t>s$. Phân biệt phương sai $t-s$ với độ lệch chuẩn $\sqrt{t-s}$.

1. Chia $[0,T]$ thành $n$ đoạn $\Delta t=T/n$. Lấy $Z_i$ độc lập chuẩn tắc và đặt $\Delta W_i=\sqrt{\Delta t}Z_i$. Tổng gia số có trung bình 0, phương sai $n\Delta t=T$.
2. Đặt $Q_n=\sum_i(\Delta W_i)^2$. Vì $E[Z^2]=1$, $E[Q_n]=T$.
3. Vì $E[Z^4]=3$, $\operatorname{Var}(Z^2)=2$, nên $\operatorname{Var}(Q_n)=2n(\Delta t)^2=2T^2/n\to0$. Vậy $Q_n\to T$ trong $L^2$; đây là lý do hạng bậc hai xuất hiện trong Itô.
4. Với $T=1,n=252$, mỗi cú sốc có độ lệch chuẩn $1/\sqrt{252}\approx0.0630$, không phải $1/252$. Một đường mô phỏng chỉ là minh họa; phép tính moment ở trên mới giải thích giới hạn.`,String.raw`Standard Brownian motion has $W_0=0$, continuous paths, independent increments and $W_t-W_s\sim N(0,t-s)$ for $t>s$. Variance is $t-s$; standard deviation is $\sqrt{t-s}$.

1. Split $[0,T]$ into $n$ intervals of length $\Delta t=T/n$. Draw independent standard normals $Z_i$ and set $\Delta W_i=\sqrt{\Delta t}Z_i$. The sum has mean zero and variance $T$.
2. Let $Q_n=\sum_i(\Delta W_i)^2$. Since $E[Z^2]=1$, $E[Q_n]=T$.
3. Since $E[Z^4]=3$, $\operatorname{Var}(Z^2)=2$. Independence gives $\operatorname{Var}(Q_n)=2T^2/n\to0$, hence $Q_n\to T$ in $L^2$. This explains the second-order Itô term.
4. For $T=1,n=252$, an increment has standard deviation $1/\sqrt{252}\approx.0630$, not $1/252$. A simulated path illustrates; the moment argument establishes the limit.`),problems:[
 exercise('T=2,n=200: độ lệch chuẩn mỗi gia số?','T=2,n=200: increment standard deviation?','Δt=0.01; √Δt=0.1.','Δt=.01; √Δt=.1.'),exercise('T=2,n=200: E[Qₙ], Var(Qₙ)?','T=2,n=200: E[Qₙ], Var(Qₙ)?','E=2; Var=2×4/200=0.04.','E=2; Var=2×4/200=.04.'),exercise('Dùng ΔW=Δt Z sẽ cho tổng phương sai nào?','If ΔW=Δt Z, what is the variance of the sum?','n(T/n)²=T²/n→0; mô hình mất ngẫu nhiên khi lưới mịn.','n(T/n)²=T²/n→0; randomness vanishes on fine grids.'),exercise('Giảm SD của Qₙ một nửa cần tăng n bao nhiêu lần?','How much larger n halves SD(Qₙ)?','SD=√2 T/√n; cần 4n.','SD=√2 T/√n; use 4n.') ]},
 {title:l('Thông tin, martingale và hai xác suất','Information, martingales and two measures'),application:l('Phân biệt dự báo lợi suất thực tế với định giá không arbitrage.','Distinguish real-world return prediction from no-arbitrage valuation.'),depth:l('Chứng minh tính martingale bằng kỳ vọng có điều kiện trong mô hình hữu hạn và Brownian. Định lý đổi độ đo tổng quát được giả định, chưa chứng minh Girsanov.','Conditional-expectation martingale checks in finite and Brownian models. General change-of-measure results are assumed; no Girsanov proof.'),lesson:l(String.raw`$\mathcal F_t$ là thông tin biết tới $t$. Quá trình khả tích $M_t$, thích nghi với thông tin đó, là martingale nếu $E[M_t\mid\mathcal F_s]=M_s$ cho $s\le t$.

1. Viết $W_t=W_s+(W_t-W_s)$. Gia số tương lai độc lập $\mathcal F_s$ và có trung bình 0, nên $E[W_t\mid\mathcal F_s]=W_s$.
2. Dùng cùng cách, $E[W_t^2\mid\mathcal F_s]=W_s^2+(t-s)$. Do đó $W_t^2-t$ cũng là martingale; $W_t^2$ riêng lẻ thì không.
3. $P$ mô tả xác suất thực để dự báo. $Q$ được chọn để giá tài sản chiết khấu là martingale trong mô hình định giá. $Q$ không khẳng định xác suất thị trường thực.
4. Với một bước $S_0=100$, giá sau một năm là 120 hoặc 80, $r=0$, điều kiện $100=q120+(1-q)80$ cho $q=0.5$. Dù xác suất tăng thực là 0.7, định giá không arbitrage trong mô hình đầy đủ này vẫn dùng 0.5.`,String.raw`$\mathcal F_t$ is information available by time $t$. An integrable adapted process is a martingale when $E[M_t\mid\mathcal F_s]=M_s$ for $s\le t$.

1. Write $W_t=W_s+(W_t-W_s)$. The future increment is independent of $\mathcal F_s$ with zero mean, so $E[W_t\mid\mathcal F_s]=W_s$.
2. Similarly $E[W_t^2\mid\mathcal F_s]=W_s^2+(t-s)$. Thus $W_t^2-t$ is a martingale, whereas $W_t^2$ is not.
3. $P$ describes real-world probabilities for prediction. $Q$ is used to make discounted asset prices martingales in a pricing model; it is not a claim about real-world frequencies.
4. In a one-year step from 100 to either 120 or 80 with $r=0$, $100=q120+(1-q)80$ gives $q=.5$. Even if the physical up probability is .7, no-arbitrage pricing in this complete model uses .5.`),problems:[
 exercise('E[W₅|F₂] bằng gì?','What is E[W₅|F₂]?','W₂: gia số từ 2 tới 5 có trung bình có điều kiện 0.','W₂: the future increment has conditional mean zero.'),exercise('E[W₅²|F₂] bằng gì?','What is E[W₅²|F₂]?','W₂²+3; vì vậy W² không phải martingale.','W₂²+3; hence W² is not a martingale.'),exercise('Trong cây 100→120/80, r=0, call K=100 giá bao nhiêu?','In the 100→120/80 tree, r=0, price a K=100 call.','Payoff 20/0; q=0.5; C=10.','Payoffs 20/0; q=.5; C=10.'),exercise('Dùng P(up)=0.7 cho giá 14. Vì sao sai cho bài định giá này?','Physical P(up)=.7 gives price 14. Why is that wrong here?','Danh mục tái tạo chỉ tốn 10, nên 14 vi phạm định giá bằng tái tạo trong mô hình không chi phí. P dùng cho dự báo, không thay Q.','Replication costs 10, so 14 violates replication pricing in this frictionless model. P predicts; it does not replace Q.') ]},
 {title:l('Itô và GBM','Itô and GBM'),application:l('Chuyển SDE thành công thức mô phỏng giá dương.','Convert an SDE into a positive-price simulation formula.'),depth:l('Áp dụng Itô một chiều và dẫn xuất GBM. Công thức Itô tổng quát được dùng như định lý; tồn tại/duy nhất SDE tổng quát chưa chứng minh.','Apply one-dimensional Itô and derive GBM. General Itô is an assumed theorem; general SDE existence/uniqueness is not proved.'),lesson:l(String.raw`Với $dX_t=a\,dt+b\,dW_t$ và hàm $f(t,x)$ đủ trơn ($C^{1,2}$), công thức Itô là
$$df=(f_t+a f_x+\tfrac12b^2f_{xx})dt+b f_xdW.$$
1. Với $dS=\mu Sdt+\sigma SdW$, chọn $f(S)=\log S$ trên $S>0$. Ta có $f'=1/S$, $f''=-1/S^2$.
2. Thế vào: $d\log S=(\mu-\sigma^2/2)dt+\sigma dW$. Hạng $-\sigma^2/2$ đến từ đạo hàm bậc hai; bỏ nó làm sai kỳ vọng giá.
3. Tích phân với hệ số hằng: $S_T=S_0\exp[(\mu-\sigma^2/2)T+\sigma\sqrt T Z]$.
4. Dùng $E[e^{aZ}]=e^{a^2/2}$, suy ra $E[S_T]=S_0e^{\mu T}$. Trong mô hình định giá không cổ tức dưới $Q$, thay $\mu$ bằng $r$; không thay bằng lợi suất alpha dự báo.`,String.raw`For $dX_t=a\,dt+b\,dW_t$ and $f\in C^{1,2}$, Itô's formula is
$$df=(f_t+a f_x+\tfrac12b^2f_{xx})dt+b f_xdW.$$
1. For $dS=\mu Sdt+\sigma SdW$, choose $f(S)=\log S$ on $S>0$. Then $f'=1/S$ and $f''=-1/S^2$.
2. Substitution gives $d\log S=(\mu-\sigma^2/2)dt+\sigma dW$. The second derivative produces the correction; omitting it changes the expected price.
3. Integrate with constant coefficients: $S_T=S_0\exp[(\mu-\sigma^2/2)T+\sigma\sqrt T Z]$.
4. Using $E[e^{aZ}]=e^{a^2/2}$ yields $E[S_T]=S_0e^{\mu T}$. Under no-dividend risk-neutral pricing, replace $\mu$ by $r$, not by a predicted alpha return.`),problems:[
 exercise('μ=0.08, σ=0.2: drift của log S?','μ=.08, σ=.2: log-price drift?','0.08−0.04/2=0.06 mỗi năm.','.08−.04/2=.06 per year.'),exercise('S₀=100, μ=0, T=1: E[S₁]?','S₀=100, μ=0, T=1: E[S₁]?','100, dù median là 100exp(−σ²/2)<100 khi σ>0.','100, although median is 100exp(−σ²/2)<100 for σ>0.'),exercise('Áp dụng Itô cho W².','Apply Itô to W².','f′=2W,f″=2: d(W²)=2W dW+dt.','f′=2W,f″=2: d(W²)=2W dW+dt.'),exercise('Bỏ −σ²/2 trong mô phỏng khiến E[Sₜ] sai bao nhiêu lần?','Omitting −σ²/2 inflates the expected price by what factor?','exp(σ²T/2). Với σ=.2,T=1: exp(.02).','exp(σ²T/2). For σ=.2,T=1: exp(.02).') ]},
 {title:l('Tái tạo và cây nhị phân','Replication and binomial trees'),application:l('Xây bộ định giá từ payoff mà không đoán xác suất thị trường.','Build a payoff pricer without guessing real-world probabilities.'),depth:l('Tái tạo một bước được dẫn xuất đầy đủ; cây nhiều bước bằng quy nạp lùi. Hội tụ cây tới BS được kiểm tra số, không chứng minh tổng quát.','One-step replication fully derived; multistep trees by backward induction. Tree-to-BS convergence checked numerically, not proved generally.'),lesson:l(String.raw`Một bước $\Delta t$, $S_u=uS$, $S_d=dS$, tài khoản tiền tăng theo $R=e^{r\Delta t}$. Cần $d<R<u$ để tránh arbitrage trong mô hình không chi phí.

1. Tìm $\Delta,B$ sao cho $\Delta uS+BR=C_u$ và $\Delta dS+BR=C_d$.
2. Trừ hai phương trình: $\Delta=(C_u-C_d)/(S(u-d))$. Thế lại: $B=(uC_d-dC_u)/(R(u-d))$.
3. Chi phí hôm nay $C=\Delta S+B=R^{-1}[qC_u+(1-q)C_d]$, $q=(R-d)/(u-d)\in(0,1)$.
4. CRR đặt $u=e^{\sigma\sqrt{\Delta t}}$, $d=1/u$. Tính payoff ở lá rồi lùi từng tầng. Không gán $q=0.5$ trừ khi công thức thật sự cho giá trị đó.
Ví dụ $S=100,u=1.2,d=.8,R=1,K=100$: $\Delta=.5,B=-40,C=10$. Ở hai trạng thái, danh mục lần lượt trả 20 và 0.`,String.raw`Over $\Delta t$, the stock becomes $uS$ or $dS$ and cash grows by $R=e^{r\Delta t}$. Frictionless no arbitrage requires $d<R<u$.

1. Solve $\Delta uS+BR=C_u$ and $\Delta dS+BR=C_d$.
2. Subtract to get $\Delta=(C_u-C_d)/(S(u-d))$, then $B=(uC_d-dC_u)/(R(u-d))$.
3. Today's replication cost is $C=\Delta S+B=R^{-1}[qC_u+(1-q)C_d]$, where $q=(R-d)/(u-d)\in(0,1)$.
4. CRR uses $u=e^{\sigma\sqrt{\Delta t}}$, $d=1/u$. Evaluate leaf payoffs then work backward. Do not assume $q=.5$.
For $S=100,u=1.2,d=.8,R=1,K=100$, $\Delta=.5,B=-40,C=10$. The portfolio pays 20 or 0, exactly matching the call.`),problems:[
 exercise('Cây ví dụ, K=110: Δ và C?','Example tree, K=110: find Δ and C.','Payoff10/0; Δ=10/40=.25; B=−20; C=5.','Payoffs10/0; Δ=10/40=.25; B=−20; C=5.'),exercise('u=1.1,d=.9,R=1.02: q?','u=1.1,d=.9,R=1.02: q?','(.12)/(.2)=.6.','(.12)/(.2)=.6.'),exercise('u=1.01,d=.99,R=1.02: lỗi gì?','u=1.01,d=.99,R=1.02: what fails?','q=1.5>1; tiền mặt tăng hơn cả nhánh tăng cổ phiếu. Không dùng cây này để định giá.','q=1.5>1; cash outgrows even the up branch. This tree violates no arbitrage.'),exercise('Tăng N gấp đôi có buộc sai số call giảm đơn điệu không?','Must doubling N monotonically reduce call-price error?','Không. Vị trí strike so với nút gây dao động; cần bảng nhiều N và benchmark BS.','No. Strike alignment can cause oscillations; compare several N values against BS.') ]},
 {title:l('PDE và Black–Scholes','PDE and Black–Scholes'),application:l('Nối tái tạo động với công thức định giá call/put.','Connect dynamic replication to European call/put formulas.'),depth:l('Dẫn xuất PDE theo lập luận hedge lý tưởng, dùng nghiệm BS. Không chứng minh giải tích nghiệm PDE tổng quát.','Derive the PDE through idealized hedging; use the BS solution. General PDE solution theory is not proved.'),lesson:l(String.raw`Giả thiết: giao dịch liên tục, không chi phí/cổ tức, được vay ở $r$, $r,\sigma$ hằng, $S>0$, thị trường GBM. Với giá $V(t,S)$ đủ trơn trước đáo hạn:

1. Itô cho $dV=(V_t+\mu SV_S+\tfrac12\sigma^2S^2V_{SS})dt+\sigma SV_SdW$.
2. Danh mục tự tài trợ giữ $\Delta=V_S$ cổ phiếu và $V-\Delta S$ tiền mặt có thay đổi $\Delta dS+r(V-\Delta S)dt$. Đồng nhất hai vế cho
$$V_t+\tfrac12\sigma^2S^2V_{SS}+rSV_S-rV=0.$$
3. Call châu Âu có điều kiện cuối $V(T,S)=(S-K)^+$. Với thời gian còn lại $\tau$, $C=S\Phi(d_1)-Ke^{-r\tau}\Phi(d_2)$, $d_1=[\log(S/K)+(r+\sigma^2/2)\tau]/(\sigma\sqrt\tau)$, $d_2=d_1-\sigma\sqrt\tau$.
4. Put–call parity: $C-P=S-Ke^{-r\tau}$ vì payoff call trừ put bằng $S_T-K$. Với $S=K=100,r=.05,\sigma=.2,\tau=1$, call ≈10.4506, put ≈5.5735.`,String.raw`Assume continuous frictionless trading, no dividends, borrowing at $r$, constant $r,\sigma$ and positive GBM prices. For smooth $V(t,S)$ before expiry:

1. Itô gives $dV=(V_t+\mu SV_S+\tfrac12\sigma^2S^2V_{SS})dt+\sigma SV_SdW$.
2. A self-financing portfolio with $\Delta=V_S$ shares and $V-\Delta S$ cash changes by $\Delta dS+r(V-\Delta S)dt$. Equating coefficients yields
$$V_t+\tfrac12\sigma^2S^2V_{SS}+rSV_S-rV=0.$$
3. A European call has terminal condition $(S-K)^+$. With time to maturity $\tau$, $C=S\Phi(d_1)-Ke^{-r\tau}\Phi(d_2)$, where $d_1=[\log(S/K)+(r+\sigma^2/2)\tau]/(\sigma\sqrt\tau)$ and $d_2=d_1-\sigma\sqrt\tau$.
4. Put–call parity is $C-P=S-Ke^{-r\tau}$ because the payoff difference is $S_T-K$. For $S=K=100,r=.05,\sigma=.2,\tau=1$, call ≈10.4506 and put ≈5.5735.`),problems:[
 exercise('Ở T=0,S=110,K=100: call và put?','At T=0,S=110,K=100: call and put?','Call10, put0; dùng payoff, không chia cho √T.','Call10, put0; use the payoff, do not divide by √T.'),exercise('σ=0: công thức call giới hạn?','At σ=0, what is the call limit?','Sₜ=S exp(rT) dưới Q; chiết khấu payoff cho max(S−K exp(−rT),0).','Sₜ=S exp(rT) under Q; discounting yields max(S−K exp(−rT),0).'),exercise('Từ call10.4506 tính put của ví dụ.','Use call10.4506 to compute the example put.','P=C−100+100exp(−.05)≈5.5735.','P=C−100+100exp(−.05)≈5.5735.'),exercise('Tại sao μ mất khỏi PDE?','Why does μ disappear from the PDE?','Hệ số μSVₛ xuất hiện ở cả option và danh mục delta; hai hạng triệt tiêu. Không có nghĩa μ thực bằng r.','The μSVₛ terms cancel between option and delta portfolio. This does not mean the real-world drift equals r.') ]},
 {title:l('Monte Carlo và khoảng sai số','Monte Carlo and error intervals'),application:l('Ước lượng giá khi tính kỳ vọng trực tiếp khó.','Estimate a price when direct expectation is difficult.'),depth:l('Ước lượng và SE được dẫn xuất từ biến độc lập; khoảng CLT là xấp xỉ. Chưa triển khai payoff đường đi hay mô hình đa yếu tố.','Estimator and SE derived for independent observations; CLT intervals are approximate. Path-dependent and multifactor pricing are not implemented.'),lesson:l(String.raw`Dưới $Q$, lấy $S_T$ theo GBM và $Y=e^{-rT}(S_T-K)^+$. Giá là $E[Y]$.

1. Với $n$ mẫu độc lập, $\hat C=n^{-1}\sum Y_i$, $s^2=\sum(Y_i-\hat C)^2/(n-1)$, $SE=s/\sqrt n$. Khi CLT phù hợp, khoảng xấp xỉ là $\hat C\pm1.96SE$.
2. Antithetic: dùng cùng $Z$ và $-Z$, tạo $A_i=[Y(Z_i)+Y(-Z_i)]/2$. Các cặp độc lập nhau, nhưng hai chân cùng cặp phụ thuộc. Tính phương sai trên $A_i$, không giả vờ có $2n$ mẫu độc lập.
3. Với call tăng theo $Z$, hai payoff thường tương quan âm nên trung bình cặp giảm phương sai. Hiệu quả phải đo bằng SE với cùng ngân sách payoff.
4. So với BS qua nhiều seed; đếm tỷ lệ khoảng chứa giá chuẩn. Một khoảng trượt không tự động chứng tỏ code sai. Test parity và giới hạn vẫn cần riêng.`,String.raw`Under $Q$, simulate GBM terminal prices and let $Y=e^{-rT}(S_T-K)^+$. The price is $E[Y]$.

1. For independent samples, $\hat C=n^{-1}\sum Y_i$, $s^2=\sum(Y_i-\hat C)^2/(n-1)$ and $SE=s/\sqrt n$. When the CLT approximation is suitable, use $\hat C\pm1.96SE$.
2. Antithetics pair $Z$ and $-Z$: $A_i=[Y(Z_i)+Y(-Z_i)]/2$. Pairs are independent but their legs are dependent. Estimate variance across pair means, not as $2n$ independent payoffs.
3. A call increases with $Z$, so paired payoffs tend to be negatively correlated. Measure actual SE reduction at an equal payoff budget.
4. Compare with BS across seeds and estimate coverage. One missed interval does not automatically imply a code bug. Parity and boundary tests remain separate requirements.`),problems:[
 exercise('s=2,n=400: SE và nửa độ rộng 95%?','s=2,n=400: SE and 95% half-width?','SE=.1; nửa độ rộng=.196.','SE=.1; half-width=.196.'),exercise('Muốn SE giảm từ .1 xuống .025 cần bao nhiêu mẫu?','How many samples reduce SE from .1 to .025?','Gấp16; từ400 thành6400, giả sử phương sai không đổi.','16 times as many: 400→6400, assuming unchanged variance.'),exercise('5000 cặp có bao nhiêu quan sát độc lập để tính SE?','How many independent observations are there in 5000 pairs?','5000 trung bình cặp; không phải10000 chân.','5000 pair means, not10000 legs.'),exercise('95% interval có nghĩa xác suất giá cố định nằm trong khoảng đã tính là .95 không?','Does a frequentist 95% interval give a .95 probability for the fixed price in the realized interval?','Không. Diễn giải là quy trình lấy mẫu lặp lại có coverage xấp xỉ95%; giá lý thuyết là hằng số.','No. The repeated-sampling procedure has approximately95% coverage; the theoretical price is fixed.') ]},
 {title:l('Greeks và sổ hedge','Greeks and the hedge ledger'),application:l('Đo sensitivity và kiểm tra vì sao hedge thực tế có sai số.','Measure sensitivities and explain practical hedging error.'),depth:l('Greeks BS giải tích và hedge rời rạc được cài đặt. Không chứng minh hedge tối ưu dưới chi phí, không mô hình thanh khoản/market impact.','Analytic BS Greeks and discrete hedging implemented. No optimal-cost hedge proof or liquidity/market-impact model.'),lesson:l(String.raw`Với call không cổ tức, $\Delta=\Phi(d_1)$, $\Gamma=\phi(d_1)/(S\sigma\sqrt T)$, $\mathrm{Vega}=S\phi(d_1)\sqrt T$. Vega này tính trên thay đổi σ bằng 1; đổi một điểm phần trăm cần chia 100.

1. Bán call thu $C_0$, mua $\Delta_0$ cổ phiếu: $B_0=C_0-\Delta_0S_0-c|\Delta_0|S_0$ với $c=\mathrm{bps}/10000$.
2. Mỗi bước: tích lãi tiền mặt $B^-_{i}=B_{i-1}e^{r\Delta t}$, quan sát $S_i$, tính delta mới chỉ từ thông tin hiện tại.
3. Trả tiền tái cân bằng: $B_i=B^-_i-(\Delta_i-\Delta_{i-1})S_i-c|\Delta_i-\Delta_{i-1}|S_i$.
4. Cuối kỳ bán hết cổ phiếu, trừ payoff. Lãi/lỗ hedge là tiền mặt cuối trừ payoff call. Lưới hữu hạn, chi phí và sai mô hình đều gây sai số; tăng số lần hedge cũng tăng turnover.
Trong lab giữ 52 lần; thay seed để nhìn đường đi khác. Để báo cáo rủi ro cần nhiều seed và phân phối lỗi, không chọn riêng đường đẹp.`,String.raw`For a no-dividend call, $\Delta=\Phi(d_1)$, $\Gamma=\phi(d_1)/(S\sigma\sqrt T)$ and $\mathrm{Vega}=S\phi(d_1)\sqrt T$. Vega is per unit change in σ; divide by 100 for one percentage point.

1. Sell the call for $C_0$ and buy $\Delta_0$ shares: $B_0=C_0-\Delta_0S_0-c|\Delta_0|S_0$, with $c=\mathrm{bps}/10000$.
2. Accrue cash $B^-_i=B_{i-1}e^{r\Delta t}$, observe $S_i$ and compute delta from currently available information.
3. Pay for rebalancing: $B_i=B^-_i-(\Delta_i-\Delta_{i-1})S_i-c|\Delta_i-\Delta_{i-1}|S_i$.
4. Liquidate all shares at expiry, then subtract the payoff. Finite rebalancing, costs and model error all cause hedge error; more frequent hedging also increases turnover.
The lab uses 52 rebalances. Change seeds to inspect other paths. Risk reporting requires an error distribution across many seeds, not one attractive path.`),problems:[
 exercise('Delta=.6, S tăng .5: xấp xỉ thay đổi call bậc một?','Delta=.6, S rises .5: first-order call change?','.6×.5=.3; bỏ qua gamma nên chỉ gần đúng.','.6×.5=.3; omitting gamma makes it approximate.'),exercise('Vega=40, σ tăng .01: xấp xỉ thay đổi giá?','Vega=40, σ rises .01: approximate price change?','40×.01=.4, không phải40.','40×.01=.4, not40.'),exercise('Delta tăng .5→.6,S=100,c=10bps: tiền trade và cost?','Delta rises .5→.6,S=100,c=10bps: trade payment and cost?','Mua.1 cổ phiếu:10; cost=.001×.1×100=.01; tiền mặt giảm10.01.','Buy.1 share for10; cost=.001×.1×100=.01; cash decreases10.01.'),exercise('Hedge lỗ trên một seed có bác bỏ công thức BS không?','Does a hedge loss on one seed refute BS?','Không: hedge rời rạc và chi phí khác giả thiết liên tục không chi phí. Kiểm tra ledger và phân phối lỗi theo lưới/seed.','No: discrete costly trading differs from continuous frictionless assumptions. Check the ledger and error distributions across grids/seeds.') ]},
 {title:l('Implied volatility và giới hạn mô hình','Implied volatility and model limits'),application:l('Đọc giá thị trường thành tham số mô hình và biết lúc phép nghịch đảo không hợp lệ.','Map a market quote into a model parameter and recognize invalid inversions.'),depth:l('Bisection một quote và kiểm tra cận được hướng dẫn để tự cài đặt. Calibration cả surface, stochastic volatility và smile arbitrage ngoài phạm vi.','Single-quote bisection and bounds specified for implementation. Surface calibration, stochastic volatility and smile arbitrage remain outside scope.'),lesson:l(String.raw`Implied volatility $\sigma_*$ giải $C_{BS}(\sigma_*)=C_{quote}$ với $S,K,r,T$ cố định. Đây là tham số khớp giá của mô hình, không phải lời khẳng định volatility tương lai.

1. Với $T>0$ và không cổ tức, call phải nằm giữa $\max(S-Ke^{-rT},0)$ và $S$. Quote ngoài cận không có nghiệm BS hợp lệ.
2. Với $\sigma>0$, Vega dương nên giá call tăng theo σ. Chọn $\sigma_{lo},\sigma_{hi}$ sao cho giá quote nằm giữa hai giá; nếu không có bracket thì báo lỗi, không ép kết quả.
3. Lấy midpoint, tính giá; nếu giá nhỏ hơn quote, nâng cận dưới; ngược lại hạ cận trên. Dừng khi sai số giá dưới dung sai hoặc số vòng đạt giới hạn. Báo cả residual và bracket cuối.
4. Ví dụ quote10.4506 với $S=K=100,r=.05,T=1$ cho σ xấp xỉ .2. Nhưng quote không có thanh khoản hoặc spread lớn sẽ làm tham số không chắc chắn. Đảo cả bid và ask để được khoảng σ.
Phần stochastic finance còn thiếu: chứng minh Girsanov tổng quát, thị trường không đầy đủ, stochastic control/HJB, American/exotic và rates. Ghi rõ những khoảng trống này trong hồ sơ.`,String.raw`Implied volatility $\sigma_*$ solves $C_{BS}(\sigma_*)=C_{quote}$ for fixed $S,K,r,T$. It is a model parameter matching a quote, not a prediction of future volatility.

1. For $T>0$ without dividends, the call lies between $\max(S-Ke^{-rT},0)$ and $S$. A quote outside these bounds has no valid BS solution.
2. Vega is positive for $\sigma>0$, so call price increases with σ. Find a bracket whose prices enclose the quote; report failure if no bracket exists.
3. Price at the midpoint. If below the quote, raise the lower bound; otherwise lower the upper bound. Stop at a declared price tolerance or iteration limit. Report the residual and final bracket.
4. Quote10.4506 with $S=K=100,r=.05,T=1$ gives σ≈.2. Illiquidity and bid–ask spread make the parameter uncertain; invert bid and ask to obtain a range.
Uncovered stochastic-finance depth includes general Girsanov proofs, incomplete markets, stochastic control/HJB, American/exotic products and rates. Keep these gaps in the evidence record.`),problems:[
 exercise('S=100,K=100,r=0,T=1: quote110 có nghiệm không?','S=100,K=100,r=0,T=1: can quote110 be inverted?','Không, call không thể vượt S=100 trong mô hình.','No, the call cannot exceed S=100 in this model.'),exercise('Bracket[.1,.5], giá midpoint thấp hơn quote: bracket mới?','Bracket[.1,.5], midpoint price below quote: new bracket?','Midpoint=.3, nên [.3,.5] vì giá tăng theo σ.','Midpoint=.3, so [.3,.5] because price increases with σ.'),exercise('Bracket rộng.4: 10 vòng bisection còn rộng bao nhiêu?','Initial width.4: width after10 bisections?','.4/2¹⁰=.000390625.','.4/2¹⁰=.000390625.'),exercise('IV tăng có chứng minh Eₚ[realized vol] tăng cùng mức không?','Does higher IV prove that expected realized volatility under P rises by the same amount?','Không. Quote còn phản ánh giá rủi ro, cung cầu và sai mô hình; Q và P khác nhau.','No. Quotes also reflect risk pricing, supply/demand and misspecification; Q and P differ.') ]}
];
