'use client';
import { useEffect,useRef,useState,type CSSProperties } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowUpRight, Asterisk, MoveUpRight } from 'lucide-react';
import { useLanguage,Text } from './providers';
import { CalendarArt,QuestArt,ShelfArt,Cutout } from './portal-art';

const portals=[{id:'daily',en:'DAILY',vi:'HẰNG NGÀY',subEn:'A little further. Every day.',subVi:'Mỗi ngày, tiến thêm một chút.',code:'24 months',Art:CalendarArt},{id:'projects',en:'PROJECTS',vi:'DỰ ÁN',subEn:'Five quests. Real discoveries.',subVi:'Năm chặng. Những khám phá thật.',code:'5 quest lines',Art:QuestArt},{id:'resources',en:'RESOURCES',vi:'THƯ VIỆN',subEn:'Good questions start here.',subVi:'Nơi khởi đầu câu hỏi hay.',code:'Free, always',Art:ShelfArt}] as const;
type Particle={id:number;type:'daily'|'projects'|'resources';x:number;y:number;dx:number;dy:number;rotate:number};

export function HomePortals(){
 const {language}=useLanguage();const router=useRouter();const [particles,setParticles]=useState<Particle[]>([]);const [entering,setEntering]=useState<{id:string;rect:DOMRect}|null>(null);const counter=useRef(0);const timers=useRef<ReturnType<typeof setTimeout>[]>([]);const cooldown=useRef<Record<string,number>>({});
 useEffect(()=>()=>{timers.current.forEach(clearTimeout)},[]);
 function burst(event:React.MouseEvent<HTMLAnchorElement>|React.FocusEvent<HTMLAnchorElement>,type:Particle['type']){
  if(window.matchMedia('(prefers-reduced-motion: reduce)').matches||Date.now()-(cooldown.current[type]||0)<4500)return;
  cooldown.current[type]=Date.now();const r=event.currentTarget.getBoundingClientRect();const set=Array.from({length:3},(_,i)=>({id:counter.current++,type,x:r.left+r.width*(.2+i*.28),y:r.top+r.height*.55,dx:(i-1)*100,dy:window.innerHeight-(r.top+r.height*.55)-65,rotate:(i-1)*25}));setParticles(p=>[...p,...set]);timers.current.push(setTimeout(()=>setParticles(p=>p.filter(x=>!set.some(s=>s.id===x.id))),4900));
 }
 function enter(event:React.MouseEvent<HTMLAnchorElement>,id:string){
  if(event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;
  if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  event.preventDefault();if(entering)return;const r=event.currentTarget.getBoundingClientRect();setEntering({id,rect:r});router.prefetch('/'+id);timers.current.push(setTimeout(()=>router.push('/'+id),650));
 }
 return <main className="home-main"><section className="home-intro"><div><p className="intro-note"><span className="small-cross">+</span><Text vi="Một không gian cho trí tò mò." en="A place for a curious mind."/></p><h1>AND I <span className="wonder-word">WONDER<svg viewBox="0 0 460 20" aria-hidden="true"><path d="M3 12Q170 0 457 9M5 16Q250 7 440 17"/></svg></span><span className="title-star"><Asterisk/></span></h1></div><p className="intro-description"><Text vi="Từ câu hỏi đầu tiên đến nghiên cứu của riêng bạn. Hành trình quant bắt đầu bằng một ngày hôm nay." en="From your first question to research of your own. Your quant journey starts with today."/></p></section><section className="portal-grid" aria-label={language==='vi'?'Chọn không gian học':'Choose your study space'}>{portals.map(({id,en,vi,subEn,subVi,code,Art})=><a key={id} href={'/'+id} className={`portal portal-${id} ${entering?.id===id?'portal-entering':''}`} onClick={e=>enter(e,id)} onMouseEnter={e=>burst(e,id)} onFocus={e=>burst(e,id)}><div className="portal-top"><span className="portal-type">{language==='vi'?{daily:'Lịch học',projects:'Phòng nghiên cứu',resources:'Tủ tri thức'}[id]:{daily:'Study calendar',projects:'Research studio',resources:'Knowledge cabinet'}[id]}</span><span className="portal-arrow"><ArrowUpRight/></span></div><div className="portal-scene"><Art/><div className="scene-ground"/></div><div className="portal-caption"><h2>{language==='vi'?vi:en}</h2><p>{language==='vi'?subVi:subEn}</p></div><div className="portal-ruler"><span>{language==='vi'?{daily:'24 tháng',projects:'5 chặng dự án',resources:'Hoàn toàn miễn phí'}[id]:code}</span><span>+</span></div></a>)}</section><footer className="home-footer"><span><i className="status-square"/><Text vi="Thiết kế để học sâu." en="Built for deep work."/></span><div><span>07.10.2026 — 06.10.2028</span><span><Text vi="4 giờ / ngày · 5 ngày / tuần" en="4 hours / day · 5 days / week"/></span></div><span className="footer-mark"><MoveUpRight size={16}/><Text vi="Cứ tiếp tục tò mò" en="Stay curious"/></span></footer><div className="particle-layer" aria-hidden="true">{particles.map((p,i)=><div className="flying-cutout" key={p.id} style={{left:p.x,top:p.y,'--dx':`${p.dx}px`,'--dy':`${p.dy}px`,'--spin':`${p.rotate}deg`} as CSSProperties}><div className="cutout-solid"><Cutout type={p.type} index={i}/></div><div className="cutout-ashes">{Array.from({length:24},(_,j)=><i key={j} style={{'--px':`${(j%6)*13}px`,'--py':`${Math.floor(j/6)*15}px`,'--ax':`${((j*37)%120)-60}px`,'--ay':`${-35-(j%5)*19}px`,'--delay':`${j%4*.04}s`} as CSSProperties}/>)}</div></div>)}</div>{entering&&<div className={`portal-flight flight-${entering.id}`} style={{'--from-x':`${entering.rect.left}px`,'--from-y':`${entering.rect.top}px`,'--from-w':`${entering.rect.width}px`,'--from-h':`${entering.rect.height}px`} as CSSProperties} aria-hidden="true"><div>{entering.id==='daily'?<CalendarArt/>:entering.id==='projects'?<QuestArt/>:<ShelfArt/>}</div></div>}</main>;
}
