'use client';
import Link from 'next/link';
import {MathMarkdown} from './math-markdown';
import {useEffect,useState} from 'react';
import {useLanguage,useSession} from './providers';
import {PLAN_STORAGE,researchStages,validDate,studyDates,type Localized} from '@/lib/learning-path';
import {placementItems,placementGroups,gradePlacement} from '@/lib/placement';
import {EVIDENCE_STORAGE,emptyResearch,validateLearningRecord,type LearningRecord,type ResearchRecord} from '@/lib/research-evidence';
import './research.css';
function download(name:string,value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export function LearningPath(){
 const {language}=useLanguage();const vi=language==='vi';const t=(x:Localized)=>x[language];const owner=useSession();
 const [record,setRecord]=useState<LearningRecord>({startDate:'2026-10-12',projects:{},independentVerification:'unverified'});
 const [loaded,setLoaded]=useState(false);const [revision,setRevision]=useState<number|null>(null);const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
 const [form,setForm]=useState<'A'|'B'>('A');const [answers,setAnswers]=useState<Record<string,string>>({});const [submitted,setSubmitted]=useState(false);const [project,setProject]=useState('P01');
 useEffect(()=>{if(owner.loading)return;try{const raw=localStorage.getItem(EVIDENCE_STORAGE+(owner.authenticated?'-owner':'-guest'));const stored=raw?validateLearningRecord(JSON.parse(raw)):null;if(stored)setRecord(stored);else {const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'});setRecord({startDate:studyDates(today,1)[0],projects:{},independentVerification:'unverified'});}}catch{}setLoaded(true);
  if(owner.authenticated)fetch('/api/learning-record').then(async r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{setRevision(data.revision);if(data.record)setMessage(vi?'Có hồ sơ trên máy chủ. Bấm “Tải bản đã lưu” để mở; bản nháp hiện tại chưa bị thay.':'A cloud record exists. Use “Load saved record” to open it; your draft has not been replaced.');}).catch(()=>setMessage(vi?'Chưa kết nối hồ sơ máy chủ. Bạn vẫn có thể lưu nháp và xuất file.':'Cloud record unavailable. You can still draft and export.'));
 },[owner.loading,owner.authenticated,vi]);
 useEffect(()=>{if(!loaded)return;try{localStorage.setItem(EVIDENCE_STORAGE+(owner.authenticated?'-owner':'-guest'),JSON.stringify(record));if(validDate(record.startDate))localStorage.setItem(PLAN_STORAGE,record.startDate);}catch{setMessage(vi?'Trình duyệt không lưu được. Hãy xuất hồ sơ trước khi đóng trang.':'Browser storage unavailable. Export your record before closing.');}},[record,loaded,owner.authenticated,vi]);
 const selected=record.projects[project]??emptyResearch();const stage=researchStages.find(s=>s.id===project)!;
 function field(key:keyof ResearchRecord,value:string){setRecord(r=>({...r,projects:{...r.projects,[project]:{...(r.projects[project]??emptyResearch()),[key]:value}}}));}
 async function cloud(load=false){setSaving(true);try{const response=await fetch('/api/learning-record',load?{}:{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({record,revision})});if(!response.ok)throw Error(response.status===409?'conflict':'save');const data=await response.json();setRevision(data.revision);if(load&&data.record){const checked=validateLearningRecord(data.record);if(!checked)throw Error();setRecord(checked);}setMessage(vi?(load?'Đã tải hồ sơ.':'Đã lưu hồ sơ riêng trên MongoDB.'):(load?'Record loaded.':'Private record saved to MongoDB.'));}catch(e){setMessage((e as Error).message==='conflict'?(vi?'Bản máy chủ đã thay đổi. Xuất bản nháp rồi tải lại trước khi lưu.':'Cloud record changed. Export your draft, then reload before saving.'):(vi?'Không lưu/tải được; bản nháp trên máy vẫn còn.':'Could not save/load; the local draft is retained.'));}finally{setSaving(false);}}
 return <main className="research-page"><header className="research-heading"><span>ML ALPHA / DERIVATIVES</span><h1>{vi?'Lộ trình của bạn':'Your learning path'}</h1><p>{vi?'Từ nền tảng tới hồ sơ nghiên cứu tự học. Năng lực nghiên cứu độc lập và trình độ PhD chưa được kiểm chứng.':'From foundations to a self-study research portfolio. Independent research ability and PhD-level competence remain unverified.'}</p></header>
 <nav className="research-tabs"><a href="#entry">{vi?'Điểm bắt đầu':'Starting point'}</a><a href="#placement">{vi?'Kiểm tra nền tảng':'Placement'}</a><a href="#outcomes">{vi?'Các chặng':'Milestones'}</a><Link href="/assessment">{vi?'Tự đánh giá':'Self-assessment'}</Link><a href="#evidence">{vi?'Hồ sơ':'Evidence'}</a><Link href="/lab">{vi?'Phòng thí nghiệm':'Laboratory'} →</Link></nav>
 <section id="entry"><h2>{vi?'Bắt đầu từ buổi 1':'Start with session 1'}</h2><div className="research-inline"><label>{vi?'Ngày bắt đầu (lịch trên thiết bị này)':'Start date (this device’s calendar)'}<input type="date" min="2020-01-01" max="2090-12-31" value={record.startDate} onChange={e=>{if(validDate(e.target.value))setRecord({...record,startDate:e.target.value});}}/></label><Link className="bold-button" href="/daily/2026-10-07?curriculum=v2">{vi?'Mở buổi đầu':'Open first lesson'} →</Link><Link href="/daily">{vi?'Xem lịch đã sắp':'View schedule'}</Link></div><p>{vi?'523 buổi, 5 ngày/tuần. Mỗi buổi: 50 phút lý thuyết + 90 phút cho 4 bài tập + 90 phút dự án + 10 phút ghi kết quả. Ngày trên URL là mã bài cố định; đổi lịch không đổi tiến độ.':'523 sessions, 5 weekdays/week. Each session: 50 minutes theory + 90 minutes for 4 problems + 90 minutes project + 10 minutes recording results. URL dates are fixed lesson identifiers; rescheduling does not change progress.'}</p><p>{vi?'Chưa giải xong thì tiếp tục buổi đó; lịch không tự xác nhận bạn đã đạt. Sửa nền tảng dùng thay giờ dự án và có thể kéo dài thời gian hoàn tất. Hai năm là ngân sách dự kiến, không phải hạn chót bắt buộc.':'If unfinished, continue the same session; the calendar never certifies mastery. Foundation repair replaces project time and can extend completion. Two years is an estimated budget, not a forced deadline.'}</p></section>
 <section id="placement"><h2>{vi?'Kiểm tra trước khi vào chương trình':'Before entering the course'}</h2><p>{vi?'16 câu số học ngắn, khoảng 25 phút. Mỗi nhóm cần ≥3/4 và đúng câu cốt lõi. Đây là ngưỡng điều hướng do chương trình đặt, chưa được kiểm định trên người học; không đánh giá đầy đủ kỹ năng chứng minh.':'16 short questions, about 25 minutes. Each domain needs ≥3/4 including its critical item. These are provisional routing thresholds, not learner-validated cutoffs; they do not fully assess proof skills.'}</p>
 <fieldset disabled={submitted}><legend>{vi?'Đề':'Form'} {form}</legend>{placementGroups.map(group=><div key={group.id} className="placement-group"><h3>{t(group.title)}</h3>{placementItems(form).filter(q=>q.group===group.id).map(q=><label key={q.id}><MathMarkdown inline>{t(q.prompt)}</MathMarkdown><input inputMode="decimal" aria-label={q.id+' '+t(q.prompt)} value={answers[q.id]??''} maxLength={40} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})}/></label>)}</div>)}</fieldset>
 {!submitted?<button className="bold-button" disabled={Object.keys(answers).filter(k=>answers[k].trim()).length<16} onClick={()=>{setSubmitted(true);setRecord({...record,diagnostic:{form,answers:{...answers},submittedAt:new Date().toISOString()}});}}>{vi?'Nộp và xem kết quả':'Submit and see results'}</button>:<div role="status"><div className="placement-results">{gradePlacement(form,answers).map(g=><article key={g.id}><h3>{t(g.title)} · {g.score}/4</h3><strong>{g.ready?(vi?'Đủ ngưỡng số học':'Numerical threshold met'):(vi?'Sửa nhóm này trước':'Repair this domain first')}</strong><p>{t(g.lesson)}</p>{placementItems(form).filter(q=>q.group===g.id).map(q=><p key={q.id}><b>{q.id}.</b> <MathMarkdown inline>{t(q.explanation)}</MathMarkdown> {q.critical&&(vi?'(Câu cốt lõi)':'(Critical item)')}</p>)}</article>)}</div><p>{vi?'Làm lại phép tính trên giấy, đổi số và tự giải mà không nhìn lời giải. Nếu vẫn sai câu cốt lõi, dùng 90 phút dự án để học lại nhóm này rồi thử đề khác sau ít nhất một ngày. Không lấy điểm trung bình để che một nhóm yếu.':'Rework the calculations on paper, change the numbers and solve without the solution. If a critical item still fails, use the 90-minute project block to repair that domain, then try the other form after at least one day. Do not average away a weak domain.'}</p><button onClick={()=>{setForm(form==='A'?'B':'A');setAnswers({});setSubmitted(false);}}>{vi?'Mở đề khác':'Open alternate form'}</button></div>}
 </section>
 <section id="outcomes"><h2>{vi?'Bạn cần chứng minh được điều gì?':'What must your work demonstrate?'}</h2><div className="evidence-legend"><p><b>{vi?'Đã học':'Studied'}</b> — {vi?'đã đánh dấu hoặc đọc; không suy ra tự giải được.':'read or checked off; does not imply unaided performance.'}</p><p><b>{vi?'Đã kiểm tra bằng code':'Computationally checked'}</b> — {vi?'chỉ đúng những fixture/invariant đã chạy.':'only the fixtures/invariants actually run.'}</p><p><b>{vi?'Tự đánh giá':'Self-assessed'}</b> — {vi?'chứng minh, câu hỏi mới, kết luận và vấn đáp do bạn tự chấm.':'proofs, novelty, conclusions and defence rated by you.'}</p><p><b>{vi?'Chưa kiểm chứng độc lập':'Independently unverified'}</b> — {vi?'trạng thái giữ nguyên trong chế độ tự học.':'this remains unchanged in self-study mode.'}</p></div>
 {researchStages.map(s=><article className="path-stage" key={s.id}><span>{s.id} · W{s.start}–{s.end}</span><h3><Link href={'/projects/'+s.id}>{t(s.title)}</Link></h3><p>{t(s.outcome)}</p><p><b>{vi?'Tiêu chí':'Criteria'}:</b> {t(s.acceptance)}</p><p className="scope-note">{t(s.limit)}</p></article>)}
 <p>{vi?'ML alpha: luyện quy trình nghiên cứu low-frequency, chưa bao phủ alpha cổ phiếu point-in-time, alternative data hay production execution. Derivatives: nền tảng định giá châu Âu và hedge, chưa đủ cho vai trò exotic/rates specialist. Execution/HJB nằm ngoài lịch chính.':'ML alpha: low-frequency research workflow, excluding point-in-time stock alpha, alternative data and production execution. Derivatives: European pricing and hedging foundations, not exotic/rates specialization. Execution/HJB remains outside the main schedule.'}</p></section>
 <section id="evidence"><h2>{vi?'Hồ sơ nghiên cứu':'Research evidence'}</h2><p>{owner.authenticated?(vi?'Bản nháp lưu trên thiết bị; bấm lưu để đồng bộ hồ sơ riêng.':'Drafts save on this device; use Save to sync the private record.'):(vi?'Bản nháp riêng trên thiết bị này; khách không sửa tiến độ của chủ web.':'Private draft on this device; visitors cannot change the owner’s progress.')}</p><label>{vi?'Dự án':'Project'}<select value={project} onChange={e=>setProject(e.target.value)}>{researchStages.map(s=><option key={s.id} value={s.id}>{s.id} · {t(s.title)}</option>)}</select></label><p>{t(stage.acceptance)}</p>
 {([{key:'question',vi:'Câu hỏi của bạn và điều gì có thể bác bỏ nó',en:'Your question and what would falsify it'},{key:'literature',vi:'Ba nguồn, kết quả liên quan và khác biệt bạn sẽ kiểm tra',en:'Three sources, relevant findings and the difference you will test'},{key:'plan',vi:'Kế hoạch: dữ liệu, split, metric, số lần thử, chi phí, điều kiện dừng',en:'Plan: data, splits, metrics, trial budget, costs and stopping rules'},{key:'proofAttempt',vi:'Lập luận tự viết trước khi xem đáp án / kiểm chứng bằng code',en:'Your reasoning before seeing a solution / code checks'},{key:'artifact',vi:'GitHub commit, manifest dữ liệu, lệnh chạy và báo cáo test',en:'GitHub commit, data manifest, run command and test report'},{key:'result',vi:'Kết quả, khoảng bất định và tất cả lần thử thất bại',en:'Results, uncertainty and all failed trials'},{key:'limitations',vi:'Giới hạn: dữ liệu đã xem, giả thiết, kết luận chưa đủ bằng chứng',en:'Limits: data already seen, assumptions and unsupported conclusions'},{key:'selfDefence',vi:'Tự vấn đáp: vì sao baseline này? điều gì làm kết luận sai? câu chưa trả lời?',en:'Self-defence: why this baseline? what invalidates the conclusion? unanswered questions?'}] as const).map(f=><label className="research-field" key={f.key}>{vi?f.vi:f.en}<textarea rows={3} maxLength={6000} value={selected[f.key]} onChange={e=>field(f.key,e.target.value)}/></label>)}
 <div className="research-inline"><button onClick={()=>download('and-i-wonder-self-study.json',{...record,exportedAt:new Date().toISOString(),verificationStatement:'Self-reported evidence. No independent review, secure examination or research novelty certification.'})}>{vi?'Xuất hồ sơ JSON':'Export evidence JSON'}</button>{owner.authenticated&&<><button disabled={saving||revision===null} onClick={()=>cloud()}>{vi?'Lưu hồ sơ riêng':'Save private record'}</button><button disabled={saving} onClick={()=>cloud(true)}>{vi?'Tải bản đã lưu':'Load saved record'}</button></>}</div><p role="status">{message}</p><strong>{vi?'Chưa được kiểm chứng độc lập':'Independently unverified'}</strong></section>
 </main>;
}
