'use client';
import Link from 'next/link';
import { useLanguage, Text } from './providers';
import { MathMarkdown } from './math-markdown';
import type { MathAssessment, MathWeek } from '@/lib/math-curriculum-types';
import './math-curriculum.css';
type Outline=Pick<MathWeek,'week'|'title'|'level'|'prerequisites'|'outcomes'|'coverage'> & {date:string; sessions:{date:string;title:{en:string;vi:string};mode?:string}[]};
export function MathSyllabus({weeks,assessments}:{weeks:Outline[];assessments:MathAssessment[]}){
 const {language}=useLanguage();const t=(v:{en:string;vi:string})=>v[language];
 return <main className="math-syllabus"><h1><Text vi="Đề cương toán" en="Mathematics syllabus"/></h1>
 <p><Text vi="523 buổi · 2.092 giờ dự kiến: 1.307,5 giờ toán, bài tập và đối chiếu; 784,5 giờ code, dữ liệu và derivatives. Hoàn thành lịch không chứng nhận năng lực nghiên cứu." en="523 sessions · 2,092 planned hours: 1,307.5 hours mathematics, problems and review; 784.5 hours code, data and derivatives. Schedule completion does not certify research ability."/></p>
 <nav className="math-topbar"><Link href="/path"><Text vi="Mục tiêu và điểm vào" en="Outcomes and placement"/></Link><Link href="/assessment"><Text vi="Tự đánh giá có bài làm" en="Attempt-based self-assessment"/></Link><Link href="/daily?curriculum=v2"><Text vi="Mở lịch v2" en="Open v2 calendar"/></Link><Link href="/daily?curriculum=v1"><Text vi="Lịch v1 — lưu trữ riêng" en="Legacy v1 — separate record"/></Link><Link href="/projects"><Text vi="Dự án toán" en="Mathematical projects"/></Link></nav>
 <details><summary><Text vi="Nhánh sửa nền tảng" en="Foundation repair route"/></summary><Text vi="Nếu calculus hoặc chứng minh yếu, dùng W02–04 để sửa. Nếu vẫn thiếu prerequisite ở W16, chuyển sang nhánh sửa nền tảng: tuần lịch 17–28 làm lại W05–16, rồi lùi bridge/graduate 12 tuần; depth W85–96 chuyển sang sau năm hai, giữ nguyên 240 phút/ngày. Dùng /path để kiểm tra nền tảng và /assessment để lưu bài làm trước khi xem rubric. Nhánh này cũng hoãn một phần derivatives/capstone theo tuần nguồn; cần kéo dài lịch để hoàn tất cả hai hướng." en="Use W02–04 to repair diagnostic gaps. If foundations still fail at W16, switch to the foundation route: calendar weeks 17–28 reconstruct W05–16, then shift bridge/graduate work by 12 weeks; defer W85–96 depth beyond year two, retaining 240 minutes/day. Use /path for placement and /assessment to record attempts before seeing rubrics. This route also defers some derivatives/capstone project weeks; extend the schedule to finish both tracks."/></details>
 <p><Link href="/daily?curriculum=v2&route=foundation"><Text vi="Mở lịch nhánh sửa nền tảng (tiến độ riêng) →" en="Open the foundation repair schedule (separate progress) →"/></Link></p><h2><Text vi="Rubric toán lưu trữ — không phải kỳ thi trong lịch hiện tại" en="Archived mathematics rubrics — not scheduled exams"/></h2>{assessments.map(a=><details key={a.id}><summary>{t(a.title)} · W{a.week}</summary><MathMarkdown>{t(a.blueprint)}</MathMarkdown><MathMarkdown>{t(a.passRule)}</MathMarkdown><MathMarkdown>{t(a.remediation)}</MathMarkdown><Link href={`/daily/${weeks.find(w=>w.week===a.week)?.date}?curriculum=v2`}><Text vi="Mở bài học của tuần này" en="Open this week’s lessons"/></Link></details>)}
 <section className="lesson-depth"><p><Text vi="Đã dạy: có bài giảng và bài tập trong phạm vi được ghi. Giới thiệu: mới biết ý tưởng. Giả định: dùng kết quả chưa chứng minh. Phác thảo: còn bước chưa làm đầy đủ. Hoãn: chưa học trong lịch này. Nhãn graduate mô tả độ khó chủ đề, không phải trình độ được chứng nhận của người học." en="Taught: instruction and exercises within the stated scope. Introduced: initial familiarity. Assumed: used without proof. Sketch: proof steps remain incomplete. Deferred: not covered in this schedule. Graduate labels describe topic difficulty, not a certified learner level."/></p></section><h2><Text vi="Đề cương và prerequisite" en="Syllabus and prerequisites"/></h2>{weeks.map(w=><details id={`week-${w.week}`} key={w.week}><summary>W{String(w.week).padStart(3,'0')} · {t(w.title)} <span className="math-badge">{w.level}</span></summary><p><Text vi="Cần học trước: " en="Prerequisites: "/>{w.prerequisites.map(p=><Link key={p} href={`#week-${p}`}>W{p} </Link>)}</p><ul>{w.outcomes.map((o,i)=><li key={i}>{t(o)}</li>)}</ul><ol>{w.sessions.map(s=><li key={s.date}><Link href={`/daily/${s.date}?curriculum=v2`}>{s.date} · {t(s.title)}</Link> · 240 min{s.mode?` · ${s.mode}`:''}</li>)}</ol><div><h3><Text vi="Độ sâu và giới hạn" en="Depth and limits"/></h3><ul>{w.coverage.map((c,i)=><li key={i}>{c.topic} · {c.status} — {c.evidence}</li>)}</ul></div></details>)}
 <h2><Text vi="Derivatives và phần chưa bao phủ" en="Derivatives and remaining scope"/></h2><p><Text vi="W65–88 có tám chương tự chứa và lab: Brownian, martingale, Itô/GBM, cây, BS/PDE, Monte Carlo, Greeks/hedge và implied volatility. Độ sâu chứng minh được ghi ở đầu từng chương. Girsanov tổng quát, exotic/rates, stochastic control/HJB và execution chưa được làm chủ trong lịch chính." en="W65–88 contains eight self-contained units and labs: Brownian motion, martingales, Itô/GBM, trees, BS/PDE, Monte Carlo, Greeks/hedging and implied volatility. Each unit states proof depth. General Girsanov, exotic/rates, stochastic control/HJB and execution are not mastered in the main schedule."/></p><Link href="/derivatives"><Text vi="Mở chương trình derivatives" en="Open the derivatives course"/> →</Link>
 </main>;
}
