'use client';
import Link from 'next/link';
import { useLanguage, Text } from './providers';
import { MathMarkdown } from './math-markdown';
import type { MathAssessment, MathWeek } from '@/lib/math-curriculum-types';
import './math-curriculum.css';
type Outline=Pick<MathWeek,'week'|'title'|'level'|'prerequisites'|'outcomes'|'coverage'> & {date:string; sessions:{date:string;title:{en:string;vi:string};mode?:string}[]};
export function MathSyllabus({weeks,assessments}:{weeks:Outline[];assessments:MathAssessment[]}){
 const {language}=useLanguage();const t=(v:{en:string;vi:string})=>v[language];
 return <main className="math-syllabus"><h1><Text vi="Đề cương toán" en="Mathematics syllabus"/></h1>
 <p><Text vi="105 tuần · 523 buổi · 2.092 giờ. Mục tiêu: nền tảng vững, các kết quả chọn lọc trong học phần graduate và chiều sâu suy luận tuần tự." en="105 weeks · 523 sessions · 2,092 hours. Target: rigorous foundations, selected graduate coursework results and sequential-inference depth."/></p>
 <nav className="math-topbar"><Link href="/daily?curriculum=v2"><Text vi="Mở lịch v2" en="Open v2 calendar"/></Link><Link href="/daily?curriculum=v1"><Text vi="Lịch v1 — lưu trữ riêng" en="Legacy v1 — separate record"/></Link><Link href="/projects"><Text vi="Dự án toán" en="Mathematical projects"/></Link></nav>
 <details><summary><Text vi="Nhánh sửa nền tảng" en="Foundation repair route"/></summary><Text vi="Nếu calculus hoặc chứng minh yếu, dùng W02–04 để sửa. Nếu vẫn thiếu prerequisite ở W16, chuyển sang nhánh sửa nền tảng: tuần lịch 17–28 làm lại W05–16, rồi lùi bridge/graduate 12 tuần; depth W85–96 chuyển sang sau năm hai, giữ nguyên 240 phút/ngày. Nếu trượt gate, dùng form B sau sửa lỗi; không tích hoàn thành để bỏ qua lỗi nghiêm trọng." en="Use W02–04 to repair diagnostic gaps. If foundations still fail at W16, switch to the foundation route: calendar weeks 17–28 reconstruct W05–16, then shift bridge/graduate work by 12 weeks; defer W85–96 depth beyond year two, retaining 240 minutes/day. After a gate failure, repair and attempt form B; a completion checkbox never waives a critical error."/></details>
 <p><Link href="/daily?curriculum=v2&route=foundation"><Text vi="Mở lịch nhánh sửa nền tảng (tiến độ riêng) →" en="Open the foundation repair schedule (separate progress) →"/></Link></p><h2><Text vi="Tiêu chí đánh giá tham khảo" en="Assessment criteria for reference"/></h2>{assessments.map(a=><details key={a.id}><summary>{t(a.title)} · W{a.week}</summary><MathMarkdown>{t(a.blueprint)}</MathMarkdown><MathMarkdown>{t(a.passRule)}</MathMarkdown><MathMarkdown>{t(a.remediation)}</MathMarkdown><Link href={`/daily/${weeks.find(w=>w.week===a.week)?.date}?curriculum=v2`}><Text vi="Mở bài học của tuần này" en="Open this week’s lessons"/></Link></details>)}
 <h2><Text vi="Đề cương và prerequisite" en="Syllabus and prerequisites"/></h2>{weeks.map(w=><details id={`week-${w.week}`} key={w.week}><summary>W{String(w.week).padStart(3,'0')} · {t(w.title)} <span className="math-badge">{w.level}</span></summary><p><Text vi="Cần học trước: " en="Prerequisites: "/>{w.prerequisites.map(p=><Link key={p} href={`#week-${p}`}>W{p} </Link>)}</p><ul>{w.outcomes.map((o,i)=><li key={i}>{t(o)}</li>)}</ul><ol>{w.sessions.map(s=><li key={s.date}><Link href={`/daily/${s.date}?curriculum=v2`}>{s.date} · {t(s.title)}</Link> · 240 min{s.mode?` · ${s.mode}`:''}</li>)}</ol><details><summary><Text vi="Phạm vi được dạy" en="Coverage boundaries"/></summary><ul>{w.coverage.map((c,i)=><li key={i}>{c.topic} · {c.status} — {c.evidence}</li>)}</ul></details></details>)}
 <h2><Text vi="Sau hai năm / nhánh thay thế" en="Beyond two years / alternative tracks"/></h2><p><Text vi="Derivatives: Brownian motion → tích phân Itô → SDE → Girsanov → định giá/PDE. Execution: point processes → intensity → stochastic control/HJB. Các nhánh này cần probability/processes và một lịch riêng; không tính vào 2.092 giờ của statistical learning. Dynamic regret và các biến thể Thompson sampling chỉ được nhận mức đã ghi trong coverage; mô phỏng không thay chứng minh." en="Derivatives: Brownian motion → Itô integration → SDEs → Girsanov → pricing/PDEs. Execution: point processes → intensities → stochastic control/HJB. These require probability/processes and a separate schedule; they are outside the 2,092-hour statistical-learning track. Dynamic regret and Thompson-sampling variants have only the depth stated in coverage; simulation is not proof."/></p>
 </main>;
}
