'use client';
import Link from 'next/link';
import { ArrowUpRight, Flag, Check, Circle } from 'lucide-react';
import { useEffect,useState } from 'react';
import { Text,useLanguage } from './providers';
import type { Note } from '@/lib/types';
import './library-project.css';

const details=[{vi:'Nền móng vững chắc',en:'Build the foundations',subVi:'Đại số tuyến tính. Xác suất. Mô phỏng.',subEn:'Linear algebra. Probability. Simulation.',symbol:'∑',time:'01—13',color:'yellow'},{vi:'Đi tìm nhân tố',en:'Find the factors',subVi:'Dữ liệu thực. Hồi quy. Suy luận thống kê.',subEn:'Real data. Regressions. Statistical inference.',symbol:'↗',time:'14—26',color:'mint'},{vi:'Đọc nhịp thời gian',en:'Read the rhythm',subVi:'Chuỗi thời gian. Dự báo. Kiểm định trung thực.',subEn:'Time series. Forecasting. Honest evaluation.',symbol:'∿',time:'27—52',color:'blue'},{vi:'Xưởng nghiên cứu',en:'Make your workbench',subVi:'Quy trình tác tử. Khả năng tái lập. Kiểm chứng.',subEn:'Agent workflows. Reproducibility. Auditing.',symbol:'⊞',time:'47—52',color:'orange'},{vi:'Câu hỏi của riêng bạn',en:'Ask your own question',subVi:'Tái lập bài báo. Thử nghiệm mở rộng. Nghiên cứu.',subEn:'Replicate a paper. Test an extension. Research.',symbol:'✳',time:'53—104',color:'paper'}];
export function ProjectQuests({projects}:{projects:Note[]}){const {language}=useLanguage();const [progress,setProgress]=useState<Record<string,{checked:Record<string,boolean>}>>({});useEffect(()=>{fetch('/api/progress').then(r=>r.ok?r.json():null).then(d=>d&&setProgress(d.notes||{})).catch(()=>{});},[]);return <main className="workspace projects-workspace"><div className="page-heading"><div><div className="breadcrumb"><Link href="/">And I Wonder</Link><span>/</span><Text vi="Dự án" en="Projects"/></div><h1><Text vi="LÀM THẬT.\nHIỂU SÂU." en="BUILD THINGS.\nUNDERSTAND MORE."/></h1></div><p><Text vi="Năm chặng nghiên cứu. Mỗi chặng để lại một điều bạn có thể giải thích, kiểm chứng và chia sẻ." en="Five research quests. Each leaves you with something you can explain, test, and share."/></p></div><div className="quest-intro-line"><span><Flag size={16}/><Text vi="Hành trình nghiên cứu" en="Your research quest lines"/></span><span><Text vi="Từ nền tảng đến nghiên cứu độc lập" en="From foundations to independent research"/></span></div><div className="quest-list">{projects.map((p,i)=>{const d=details[i];const total=(p.body.match(/^- \[[ xX]\]/gm)||[]).length;const states=(p.body.match(/^- \[[ xX]\]/gm)||[]).map((task,j)=>progress[p.id]?.checked[`${p.id}::${j}`]??/\[[xX]\]/.test(task));const checked=states.filter(Boolean).length;return <Link prefetch={false} className={`quest-row quest-${d.color}`} href={`/projects/${String(p.meta.project||`P0${i+1}`)}?curriculum=v1`} key={p.id}><div className="quest-emblem"><span>{d.symbol}</span><small>0{i+1}</small></div><div className="quest-copy"><div className="quest-overline"><span><Text vi="Tuần" en="Weeks"/> {d.time}</span><span className="quest-id">P0{i+1}</span></div><h2>{language==='vi'?d.vi:d.en}</h2><p>{language==='vi'?d.subVi:d.subEn}</p><code>{String(p.meta.repository||p.title)}</code></div><div className="quest-milestones"><span><Text vi="Các mốc hoàn thành" en="Completion milestones"/></span><div>{Array.from({length:total||5},(_,j)=><i key={j} className={states[j]?'achieved':''}>{states[j]?<Check size={14}/>:<Circle size={10}/>}</i>)}</div><small>{checked}/{total} <Text vi="đã hoàn thành" en="completed"/></small></div><span className="quest-open"><ArrowUpRight size={28}/></span></Link>})}</div><div className="quest-bottom"><span className="giant-asterisk">✳</span><p><Text vi="Một kết quả âm được kiểm chứng cẩn thận vẫn là một kết quả nghiên cứu tốt." en="A carefully tested negative result is still a good research result."/></p><Link className="text-link" href="/notes/GitHub%20Publishing%20Checklist"><Text vi="Hướng dẫn đưa dự án lên GitHub" en="Your GitHub publishing checklist"/><ArrowUpRight size={16}/></Link></div></main>}
