'use client';
import Link from 'next/link';
import {MathMarkdown} from './math-markdown';
import {useMemo,useState} from 'react';
import {useLanguage} from './providers';
import {alphaBacktest,blackScholes,binomialCall,monteCarloCall,hedgePath,pairedBlockInterval,type MarketRow,type AlphaSpec} from '@/lib/quant-lab';
import './research.css';
type Data={rows:MarketRow[];manifest:{sha256:string;url:string;first:string;last:string;observations:number;[key:string]:unknown}};
type Trial={at:string;spec:AlphaSpec;partition:string;mse:number;net:number;dataHash:string};
function exportJSON(name:string,body:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(body,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export function LineChart({series,xLabel,yLabel}:{series:{name:string;color:string;values:number[]}[];xLabel:string;yLabel:string}){
 const values=series.flatMap(s=>s.values);const min=Math.min(...values),max=Math.max(...values);const span=max-min||1;const low=min-.1*span,high=max+.1*span;const x=(i:number,n:number)=>64+i/Math.max(n-1,1)*600,y=(v:number)=>240-(v-low)/(high-low)*210;
 return <svg className="lab-chart" viewBox="0 0 700 320" role="img" aria-label={`${yLabel}; ${xLabel}. ${series.map(s=>s.name).join(', ')}`}><title>{yLabel} — {xLabel}</title>{Array.from({length:5},(_,i)=>{const v=low+(high-low)*i/4;return <g key={i}><line x1="64" x2="664" y1={y(v)} y2={y(v)} stroke="#d8e0e1"/><text x="56" y={y(v)+4} textAnchor="end" fontSize="11">{v.toFixed(2)}</text></g>;})}<line x1="64" y1="240" x2="664" y2="240" stroke="#20313b"/>{series.map(s=><g key={s.name}><path d={s.values.map((v,i)=>`${i?'L':'M'}${x(i,s.values.length)},${y(v)}`).join(' ')} fill="none" stroke={s.color} strokeWidth="3"/></g>)}<text x="64" y="19" fontSize="12">{yLabel}</text><text x="364" y="266" fontSize="12" textAnchor="middle">{xLabel}</text>{series.map((s,i)=><g key={s.name} transform={`translate(${64+i*290},296)`}><line x2="22" stroke={s.color} strokeWidth="3"/><text x="29" y="4" fontSize="12">{s.name}</text></g>)}</svg>;
}
function DerivativesLab(){const vi=useLanguage().language==='vi';const [p,setP]=useState({spot:100,strike:100,rate:.05,vol:.2,years:1});const [steps,setSteps]=useState(100);const [cost,setCost]=useState(5);const [seed,setSeed]=useState(42);
 const result=useMemo(()=>{const bs=blackScholes(p),mc=monteCarloCall(p,5000,seed),hedge=hedgePath(p,52,cost,seed);let tree:number|null=null;try{tree=binomialCall(p,steps);}catch{}return {bs,mc,hedge,tree};},[p,steps,cost,seed]);
 const curve=Array.from({length:61},(_,i)=>blackScholes({...p,spot:40+i*2}));
 return <section><div className="research-inline"><h2>{vi?'Định giá và hedge':'Pricing and hedging'}</h2><Link href="/derivatives">{vi?'Bài giảng từng bước':'Step-by-step lessons'} →</Link></div><MathMarkdown>{vi?'Call/put châu Âu, không cổ tức, r và σ hằng; mô phỏng dưới Q. Vega hiển thị cho một điểm phần trăm σ. Tại payoff gấp khúc, đạo hàm không xác định; delta 0.5 chỉ là quy ước hiển thị.':'European calls/puts, no dividends, constant r and σ; simulation under Q. Vega is per percentage point of σ. At the payoff kink the derivative is undefined; delta .5 is only a display convention.'}</MathMarkdown>
 <div className="lab-grid"><div className="lab-controls">{([{key:'spot',label:'S',min:40,max:160,step:1},{key:'strike',label:'K',min:40,max:160,step:1},{key:'rate',label:'r',min:-.02,max:.15,step:.005},{key:'vol',label:'σ',min:0,max:1,step:.01},{key:'years',label:'T',min:0,max:3,step:.05}] as const).map(c=><label key={c.key}><MathMarkdown inline>{`$${c.key==='vol'?'\\sigma':c.label} = ${p[c.key].toFixed(2)}$`}</MathMarkdown><input type="range" min={c.min} max={c.max} step={c.step} value={p[c.key]} aria-label={c.label} onChange={e=>setP({...p,[c.key]:Number(e.target.value)})}/></label>)}<label>{vi?'Bước cây':'Tree steps'}: {steps}<input type="range" min="10" max="300" step="10" value={steps} onChange={e=>setSteps(Number(e.target.value))}/></label><label>{vi?'Chi phí hedge (bps)':'Hedge cost (bps)'}: {cost}<input type="range" min="0" max="50" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label><label>Seed<input type="number" min="1" max="999999" value={seed} onChange={e=>setSeed(Math.min(999999,Math.max(1,Number(e.target.value))))}/></label></div><div><LineChart series={[{name:'Call',color:'#346486',values:curve.map(v=>v.call)},{name:'Put',color:'#976328',values:curve.map(v=>v.put)}]} xLabel="S: 40 → 160" yLabel={vi?'Giá option':'Option price'}/><div className="lab-metrics"><div>Call<b>{result.bs.call.toFixed(4)}</b></div><div>Put<b>{result.bs.put.toFixed(4)}</b></div><div>Delta<b>{result.bs.delta.toFixed(4)}</b></div><div>Gamma<b>{result.bs.gamma.toFixed(4)}</b></div><div>Vega / 1%<b>{(result.bs.vega/100).toFixed(4)}</b></div></div><p>CRR: {result.tree===null?(vi?'q nằm ngoài [0,1]; tăng số bước.':'q is outside [0,1]; increase steps.'):result.tree.toFixed(4)} · MC: {result.mc.estimate.toFixed(4)}, SE {result.mc.se.toFixed(4)} · 95% [{result.mc.lower.toFixed(4)}, {result.mc.upper.toFixed(4)}]</p><MathMarkdown>{vi?'5.000 cặp antithetic, 10.000 payoff. Khoảng 95% xấp xỉ theo CLT trên trung bình cặp; một khoảng có thể không chứa giá lý thuyết.':'5,000 antithetic pairs, 10,000 payoffs. Approximate 95% CLT interval across pair means; a particular interval can miss the theoretical price.'}</MathMarkdown><MathMarkdown>{`Put–call parity: $C-P-S+Ke^{-rT}=${(result.bs.call-result.bs.put-p.spot+p.strike*Math.exp(-p.rate*p.years)).toFixed(8)}$.`}</MathMarkdown></div></div>
 <h3>{vi?'Một đường hedge, 52 lần tái cân bằng':'One hedge path, 52 rebalances'}</h3><LineChart series={[{name:vi?'Tài sản cơ sở':'Underlying',color:'#346486',values:result.hedge.ledger.map(r=>r.spot)}]} xLabel={vi?'Bước 0 → 52, cách đều theo thời gian':'Step 0 → 52, equally spaced in time'} yLabel="S"/><p>{vi?'Bán call tại giá lý thuyết rồi mua delta cổ phiếu; sổ tiền mặt tích lãi, trừ mọi giao dịch và chi phí, thanh lý cổ phiếu ở cuối kỳ. Sai số = tài sản hedge cuối kỳ − payoff.':'Sell a call at the theoretical price and buy delta shares; cash accrues interest and pays trades and costs, with final stock liquidation. Error = terminal hedge assets − payoff.'} <b>{result.hedge.error.toFixed(4)}</b>. {vi?'Một đường mô phỏng không đo được phân phối rủi ro hedge.':'One simulated path does not measure the hedge-risk distribution.'}</p><button onClick={()=>exportJSON('derivatives-experiment.json',{inputs:p,steps,costBps:cost,seed,...result,independentVerification:'unverified'})}>{vi?'Xuất phép thử và sổ tiền mặt':'Export experiment and cash ledger'}</button>
 </section>;
}
function AlphaLab(){const vi=useLanguage().language==='vi';const [data,setData]=useState<Data>();const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [spec,setSpec]=useState<AlphaSpec>({lookback:3,lambda:1,costBps:10});const [partition,setPartition]=useState<'validation'|'test'>('validation');const [result,setResult]=useState<ReturnType<typeof alphaBacktest>>();const [trials,setTrials]=useState<Trial[]>([]);const [plan,setPlan]=useState('');const [frozen,setFrozen]=useState<{at:string;plan:string;spec:AlphaSpec;dataHash:string}>();const [exposure,setExposure]=useState<string>();
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/market-data');if(!r.ok)throw Error();const d:Data=await r.json();setData(d);setResult(undefined);setFrozen(undefined);setPartition('validation');setExposure(undefined);try{const history=JSON.parse(localStorage.getItem('wonder-alpha-'+d.manifest.sha256)??'{}');if(Array.isArray(history.trials))setTrials(history.trials.slice(-200));else setTrials([]);if(typeof history.exposure==='string')setExposure(history.exposure);}catch{setTrials([]);}}catch{setError(vi?'Chưa tải được dữ liệu miễn phí từ nguồn. Thử lại sau; không thay bằng dữ liệu giả.':'Free provider data unavailable. Retry later; no synthetic data substituted.');}finally{setLoading(false);}}
 function run(test=false){if(!data)return;const settings=test?frozen?.spec:spec;if(!settings)return;const part=test?'test':'validation';const res=alphaBacktest(data.rows,settings,part);const at=new Date().toISOString();const history=[...trials,{at,spec:{...settings},partition:part,mse:res.mse,net:res.points.at(-1)!.equity-1,dataHash:data.manifest.sha256}].slice(-200);const viewed=test?(exposure??at):exposure;setTrials(history);setExposure(viewed);setPartition(part);setResult(res);try{localStorage.setItem('wonder-alpha-'+data.manifest.sha256,JSON.stringify({trials:history,exposure:viewed}));}catch{setError(vi?'Không lưu được lịch sử trên trình duyệt; hãy xuất hồ sơ.':'Browser history could not be stored; export your record.');}}
 const interval=useMemo(()=>result?pairedBlockInterval(result.points):null,[result]);
 return <section><h2>{vi?'ML alpha · dữ liệu thị trường':'ML alpha · market data'}</h2><MathMarkdown>{vi?'Mô hình ridge một feature: trung bình lợi suất vượt trội của L tháng trước dự đoán tháng kế tiếp. Fit một lần trên 60% đầu, chọn L/λ trên 20% tiếp, giữ 20% cuối để đánh giá. Không phải mô hình alpha đã chứng minh hiệu quả.':'Single-feature ridge: mean excess return over the preceding L months predicts the next month. Fit once on the first 60%, select L/λ on the next 20%, hold out the final 20%. This is not an established profitable alpha model.'}</MathMarkdown><button onClick={load} disabled={loading}>{loading?(vi?'Đang tải…':'Loading…'):(vi?'Tải dữ liệu Ken French miễn phí':'Load free Ken French data')}</button>{error&&<p className="lab-error" role="status">{error}</p>}
 {data&&<><p><a href={data.manifest.url}>{vi?'Nguồn CSV gốc':'Original CSV source'}</a> · {data.manifest.first} → {data.manifest.last} · {data.manifest.observations} {vi?'tháng':'months'}</p><details><summary>{vi?'Phiên bản và giới hạn dữ liệu':'Data version and limits'}</summary><code>SHA-256: {data.manifest.sha256}</code><MathMarkdown>{vi?'Factor thị trường tổng hợp, đã được nhà cung cấp sửa đổi. Không có universe cổ phiếu, delisting hay timestamp công bố ban đầu. FIZ được thay bằng CIZ từ bản phát hành tháng 1/2025. Feature được lag không biến dữ liệu sửa đổi thành dữ liệu point-in-time.':'Aggregate market factor returns revised by the provider. No stock universe, delistings or original publication timestamps. FIZ was replaced by CIZ in the January 2025 release. Lagging features does not turn revised data into point-in-time data.'}</MathMarkdown></details><div className="research-inline"><label><MathMarkdown inline>{'$L$'}</MathMarkdown><select value={spec.lookback} onChange={e=>{setSpec({...spec,lookback:Number(e.target.value)});setResult(undefined);setFrozen(undefined);}}>{[1,3,12].map(n=><option key={n}>{n}</option>)}</select></label><label><MathMarkdown inline>{'$\\lambda$'}</MathMarkdown><select value={spec.lambda} onChange={e=>{setSpec({...spec,lambda:Number(e.target.value)});setResult(undefined);setFrozen(undefined);}}>{[0,1,10].map(n=><option key={n}>{n}</option>)}</select></label><label>{vi?'Chi phí mỗi đơn vị turnover (bps)':'Cost per unit turnover (bps)'}<input type="number" min="0" max="1000" value={spec.costBps} onChange={e=>{setSpec({...spec,costBps:Math.max(0,Math.min(1000,Number(e.target.value)))});setResult(undefined);setFrozen(undefined);}}/></label><button onClick={()=>run()}>{vi?'Chạy validation':'Run validation'}</button></div><MathMarkdown>{vi?'9 cấu hình L/λ. Scaler chỉ học trên train; vị thế long 1 khi dự đoán >0, còn lại giữ tiền mặt. Lợi suất = RF + vị thế × (Rm−RF) − chi phí × turnover. Có chi phí vào lệnh và thanh lý cuối tập cho cả chiến lược lẫn benchmark.':'9 L/λ configurations. Scaling uses training data only; long 1 when the prediction is positive, otherwise hold cash. Return = RF + position × (Rm−RF) − cost × turnover. Entry and final liquidation costs apply to both strategy and benchmark.'}</MathMarkdown>
 <label className="research-field">{vi?'Trước khi mở holdout: giả thuyết, metric chính, lựa chọn tham số, điều kiện bác bỏ':'Before opening holdout: hypothesis, primary metric, parameter choice and falsification rule'}<textarea rows={3} maxLength={6000} value={plan} disabled={Boolean(frozen)} onChange={e=>setPlan(e.target.value)}/></label><div className="research-inline"><button disabled={plan.trim().length<40||Boolean(frozen)} onClick={()=>setFrozen({at:new Date().toISOString(),plan,spec:{...spec},dataHash:data.manifest.sha256})}>{vi?'Chốt kế hoạch này':'Freeze this plan'}</button><button disabled={!frozen} onClick={()=>run(true)}>{vi?'Mở kết quả holdout':'Reveal holdout result'}</button>{frozen&&<button onClick={()=>{setFrozen(undefined);setResult(undefined);}}>{vi?'Sửa kế hoạch':'Revise plan'}</button>}</div><p className="scope-note">{exposure?(vi?'Holdout đã được xem: ':'Holdout already exposed: ')+exposure:(vi?'Chưa ghi nhận mở holdout trên thiết bị này.':'No holdout exposure recorded on this device.')}{' '}{vi?'Đây là nhật ký tự học trên trình duyệt, không phải đăng ký nghiên cứu độc lập hay kỳ thi bảo mật. Đổi thiết bị/xóa storage có thể mất lịch sử. Khi đã xem test, mọi điều chỉnh tiếp theo là exploratory.':'This is a browser self-study log, not independent preregistration or a secure exam. Device changes/storage deletion can lose history. After test exposure, further tuning is exploratory.'}</p>
 {result&&<><h3>{partition==='test'?'Holdout':'Validation'} · {result.points[0].date} → {result.points.at(-1)!.date}</h3><LineChart series={[{name:vi?'Chiến lược sau chi phí':'Strategy after costs',color:'#346486',values:[1,...result.points.map(p=>p.equity)]},{name:vi?'Thị trường sau chi phí':'Market after costs',color:'#976328',values:[1,...result.points.map(p=>p.benchmarkEquity)]}]} xLabel={`${result.points[0].date} → ${result.points.at(-1)!.date} (${vi?'tháng':'monthly'})`} yLabel={vi?'Tài sản ban đầu = 1':'Initial wealth = 1'}/><div className="lab-metrics"><div>MSE<b>{result.mse.toFixed(6)}</b></div><div>{vi?'MSE baseline hằng':'Constant baseline MSE'}<b>{result.baselineMse.toFixed(6)}</b></div><div>Drawdown<b>{(result.drawdown*100).toFixed(2)}%</b></div></div><p>{vi?'Chênh lệch lợi suất tháng so với thị trường, bootstrap vòng theo block 6 tháng, 1.000 lần:':'Monthly return difference versus the market, circular 6-month block bootstrap, 1,000 replicates:'} {(interval!.mean*100).toFixed(3)}%; 95% [{(interval!.lower*100).toFixed(3)}, {(interval!.upper*100).toFixed(3)}]%. {vi?'Giả định cấu trúc phụ thuộc đủ ổn định; không hiệu chỉnh việc chọn mô hình qua nhiều lần thử.':'Assumes sufficiently stable dependence; does not correct for model selection across trials.'}</p><button onClick={()=>exportJSON('alpha-research-record.json',{manifest:data.manifest,snapshot:data.rows,frozenPlan:frozen,holdoutFirstViewed:exposure,trials,result,interval,independentVerification:'unverified'})}>{vi?'Xuất dữ liệu, kế hoạch và kết quả':'Export data, plan and results'}</button></>}
 <details><summary>{vi?'Nhật ký lần thử':'Trial log'} ({trials.length}/200)</summary><div className="lab-table-wrap"><table><thead><tr><th>{vi?'Thời điểm':'Time'}</th><th>Split</th><th>L / λ / bps</th><th>MSE</th><th>{vi?'Lợi suất':'Return'}</th></tr></thead><tbody>{trials.map((r,i)=><tr key={i}><td>{r.at}</td><td>{r.partition}</td><td>{r.spec.lookback} / {r.spec.lambda} / {r.spec.costBps}</td><td>{r.mse.toFixed(6)}</td><td>{(r.net*100).toFixed(2)}%</td></tr>)}</tbody></table></div><MathMarkdown>{vi?'Giữ 200 lần gần nhất trên thiết bị. Xuất trước khi vượt giới hạn để lưu lịch sử đầy đủ.':'Keeps the latest 200 device-local trials. Export before exceeding the limit to retain full history.'}</MathMarkdown></details></>}
 </section>;
}
export function QuantLab(){const vi=useLanguage().language==='vi';const [tab,setTab]=useState<'alpha'|'derivatives'>('alpha');return <main className="research-page"><header className="research-heading"><span>RESEARCH LAB</span><h1>{vi?'Từ mô hình tới phép thử':'From models to experiments'}</h1></header><nav className="research-tabs"><button aria-pressed={tab==='alpha'} onClick={()=>setTab('alpha')}>ML alpha</button><button aria-pressed={tab==='derivatives'} onClick={()=>setTab('derivatives')}>Derivatives</button><Link href="/path#evidence">{vi?'Hồ sơ nghiên cứu':'Research evidence'}</Link><a href="/research-kit/research.py" download>{vi?'Tải code Python chạy ngoài web':'Download runnable Python code'}</a></nav>{tab==='alpha'?<AlphaLab/>:<DerivativesLab/>}</main>;}
