import { bi, type LabKind, type LabSpec } from './math-labs';
const titles:Record<LabKind,ReturnType<typeof bi>>={
 quadratic:bi('Derivative and finite-difference laboratory','Thí nghiệm đạo hàm và sai phân'),convex:bi('Curvature, Hessian and convexity','Độ cong, Hessian và tính lồi'),ols:bi('Fit a line and inspect residuals','Khớp đường thẳng và kiểm tra phần dư'),bayes:bi('Bayes: follow the denominator','Bayes: theo dõi mẫu số'),binomial:bi('Explore the binomial distribution','Khám phá phân phối nhị thức'),normal:bi('Normal density and tail probability','Mật độ chuẩn và xác suất đuôi'),exponential:bi('Waiting time and survival','Thời gian chờ và hàm sống'),convergence:bi('An epsilon bound you can manipulate','Điều chỉnh ngưỡng epsilon'),constraint:bi('A constraint moves the optimum','Ràng buộc thay đổi điểm tối ưu'),descent:bi('When does gradient descent converge?','Khi nào gradient descent hội tụ?'),kalman:bi('A Kalman update as a weighted compromise','Cập nhật Kalman như một phép cân bằng'),ewma:bi('Watch the state update over time','Theo dõi cập nhật trạng thái theo thời gian'),ar:bi('Recursive AR(1) forecasts','Dự báo AR(1) đệ quy'),beta:bi('From prior to posterior','Từ tiên nghiệm đến hậu nghiệm'),prox:bi('Soft thresholding and sparsity','Ngưỡng mềm và tính thưa'),portfolio:bi('Portfolio variance across weights','Phương sai danh mục theo tỷ trọng'),chebyshev:bi('Sample size and Chebyshev bounds','Cỡ mẫu và cận Chebyshev'),hoeffding:bi('Concentration for bounded IID data','Tập trung cho dữ liệu IID bị chặn'),wilson:bi('Compare Wald and Wilson intervals','So sánh khoảng Wald và Wilson')};
const spec=(kind:LabKind,defaults:Record<string,number>,data?:number[][],note?:ReturnType<typeof bi>):LabSpec=>({kind,title:titles[kind],defaults,data,note});
/** Explicit fixtures for the actual exercises. No keyword-based reassignment. */
export const exerciseLabs:Record<string,LabSpec>={
 '1-0':spec('quadratic',{a:3,b:6,x:1,h:.01}),
 '1-1':spec('ols',{intercept:0,slope:0},[[0,1],[1,2],[2,3]],bi('This explores the fitted line. The duplicate-column argument is in the step-by-step solution.','Phần này khám phá đường khớp. Lập luận về cột trùng nằm trong lời giải từng bước.')),
 '1-2':spec('bayes',{prior:.02,sensitivity:.9,fpr:.05}),
 '1-3':spec('convergence',{scale:3,epsilon:.02,n:151}),
 '2-3':spec('bayes',{prior:.3,sensitivity:.8,fpr:.2},undefined,bi('A=red, B=success. The P(B) metric answers the total-probability question.','A=đỏ, B=thành công. Chỉ số P(B) trả lời câu hỏi xác suất toàn phần.')),
 '4-2':spec('convex',{a:2,b:-1,c:3,theta:.5},[[-1,0],[1,1]],bi('The surface is the unshifted f=2x²−2xy+3y² from this problem. Adding −2x+y changes the minimizer but not the Hessian.','Mặt cong là f=2x²−2xy+3y² gốc của đề. Thêm −2x+y đổi điểm tối ưu nhưng không đổi Hessian.')),
 '4-3':spec('bayes',{prior:.04,sensitivity:.7,fpr:.05},undefined,bi('A=G₁, B=positive. Read P(B) for the overall positive rate.','A=G₁, B=dương tính. Đọc P(B) để biết tỷ lệ dương tính toàn dân số.')),
 '4-4':spec('bayes',{prior:.02,sensitivity:.9,fpr:.05}),
 '5-1':spec('ols',{intercept:0,slope:0},[[0,1],[1,2],[2,2]]),
 '5-2':spec('binomial',{n:8,p:.3,k:2}),
 '5-3':spec('ols',{intercept:0,slope:0},[[0,2],[1,1],[2,4]],bi('This lab covers the OLS part; the separate Bernoulli sum is addressed in the worked answer.','Thí nghiệm này cho phần OLS; tổng Bernoulli riêng được xử lý trong lời giải.')),
 '5-4':spec('ols',{intercept:0,slope:0},[[-1,1],[0,2],[1,4]]),
 '6-0':spec('convex',{a:2.5,b:1,c:1,theta:.5},undefined,bi('Here H=A=[[5,2],[2,2]]. We visualize ½vᵀAv to show the given matrix eigenvalues as curvature.','Ở đây H=A=[[5,2],[2,2]]. Ta vẽ ½vᵀAv để biểu diễn trị riêng của ma trận đã cho qua độ cong.')),
 '6-1':spec('normal',{mu:50,sd:10,x:40}),
 '6-2':spec('exponential',{rate:.25,t:4}),
 '9-3':spec('chebyshev',{variance:16,n:100,epsilon:.5}),
 '9-4':spec('chebyshev',{variance:.24,n:960,epsilon:.05}),
 '10-1':spec('binomial',{n:80,p:.25,k:26},undefined,bi('Exact binomial tail for comparison with the normal approximation requested in the problem.','Đuôi nhị thức chính xác để so sánh với xấp xỉ chuẩn được yêu cầu trong đề.')),
 '10-2':spec('binomial',{n:40,p:.5,k:16},undefined,bi('For P(X≤15), subtract the displayed P(X≥16) from 1.','Với P(X≤15), lấy 1 trừ P(X≥16) đang hiển thị.')),
 '11-0':spec('wilson',{n:2500,fraction:.25}),
 '11-1':spec('wilson',{n:20,fraction:0}),
 '13-2':spec('wilson',{n:900,fraction:170/900}),
 '31-0':spec('ar',{c:-.1,phi:.75,initial:2,noise:.1},undefined,bi('Only conditional means are specified in this exercise. Innovation variance .1 is an illustrative extra assumption used only for the variance metric.','Đề chỉ xác định trung bình có điều kiện. Phương sai nhiễu 0,1 là giả định minh họa bổ sung, chỉ dùng cho chỉ số phương sai.')),
 '31-1':spec('ols',{intercept:0,slope:0},[[0,1],[1,1],[1,3]]),
 '31-2':spec('ar',{c:.4,phi:.6,initial:5,noise:.1},undefined,bi('Variance .1 is illustrative; the exercise determines only the mean path.','Phương sai 0,1 chỉ minh họa; đề chỉ xác định đường trung bình.')),
 '31-3':spec('ar',{c:1,phi:.5,initial:6,noise:.36}),
 '32-2':spec('ewma',{alpha:.5,initial:.002},[[.0016,.0004]],bi('State=v, observations=r², and α=1−λ. Values use squared-return units.','Trạng thái=v, quan sát=r², và α=1−λ. Đơn vị là bình phương lợi suất.')),
 '34-0':spec('kalman',{mean:3,variance:9,observation:7,noise:3}),
 '34-2':spec('kalman',{mean:5,variance:1.5,observation:9,noise:3},undefined,bi('P⁻=P+Q. Start at 1.5 for Q=.5; change P⁻ to 4 for Q=3.','P⁻=P+Q. Bắt đầu 1,5 khi Q=0,5; đổi P⁻ thành 4 khi Q=3.')),
 '36-2':spec('constraint',{center:3,bound:2,x:2,offset:-9}),
 '36-3':spec('portfolio',{v1:1,v2:9,rho:0,weight:.75}),
 '37-0':spec('constraint',{center:3,bound:1,x:1}),
 '38-2':spec('descent',{curvature:4,eta:.2,x0:1,steps:2}),
 '45-1':spec('quadratic',{a:4,b:1,x:.5,h:.01},undefined,bi('Use f′(w) from the lab in w_new=w−.05f′(w).','Dùng f′(w) từ thí nghiệm trong w_mới=w−0,05f′(w).')),
 '45-2':spec('descent',{curvature:5,eta:.1,x0:1,steps:6}),
 '57-0':spec('chebyshev',{variance:9,n:1,epsilon:6},undefined,bi('This is the Chebyshev portion. The separate Markov bound is in the solution.','Đây là phần Chebyshev. Cận Markov riêng nằm trong lời giải.')),
 '57-1':spec('hoeffding',{n:100,epsilon:.1}),
 '57-4':spec('chebyshev',{variance:.25,n:1000,epsilon:.05}),
 '64-0':spec('beta',{alpha:2,beta:2,success:7,failure:3}),
 '64-1':spec('beta',{alpha:9,beta:5,success:0,failure:0}),
 '69-0':spec('prox',{lambda:.5,eta:.2,v:.05},undefined,bi('Try each given coordinate v=.05, −.4, 1; the same threshold applies independently.','Thử từng tọa độ v=0,05; −0,4; 1; cùng ngưỡng được áp dụng độc lập.')),
 '69-1':spec('prox',{lambda:.5,eta:1,v:3},undefined,bi('The smooth gradient step gives v=3. The lab applies its proximal step.','Bước gradient của phần trơn cho v=3. Thí nghiệm áp dụng bước proximal tiếp theo.')),
 '69-4':spec('prox',{lambda:.5,eta:1,v:3}),
 '75-0':spec('quadratic',{a:3,b:6,x:1,h:.01}),
 '75-3':spec('quadratic',{a:1,b:2,x:.5,h:.1}),
 '82-0':spec('quadratic',{a:1,b:4,x:0,h:.01}),
 '82-2':spec('ewma',{alpha:.25,initial:4},[[10,2]]),
 '82-3':spec('descent',{curvature:1,eta:.25,x0:4,steps:3}),
 '89-2':spec('ewma',{alpha:.25,initial:2},[[6,6]]),
 '103-0':spec('bayes',{prior:.2,sensitivity:.8,fpr:.1}),
 '103-1':spec('binomial',{n:10,p:.5,k:8}),
 '103-2':spec('constraint',{center:4,bound:1,x:1}),
};
/** These defaults reproduce the lesson example rather than the separate exercise. */
export const theoryLabs:Record<string,LabSpec>={
 '1-0':spec('quadratic',{a:2,b:3,x:1,h:.01}),
 '1-1':spec('ols',{intercept:7/6,slope:.5},[[0,1],[1,2],[2,2]]),
 '1-2':spec('bayes',{prior:.01,sensitivity:.9,fpr:.05}),
 '1-3':spec('convergence',{scale:1,epsilon:.05,n:21}),
 '1-4':spec('wilson',{n:10,fraction:.4},undefined,bi('The given sample is k=4 in n=10. Wilson and Wald intervals extend the standard-error example.','Mẫu đã cho là k=4 trong n=10. Khoảng Wilson và Wald mở rộng ví dụ sai số chuẩn.')),
 '4-2':spec('convex',{a:1,b:.5,c:2,theta:.5},[[-1,0],[1,1]],bi('Start with f=x²+xy+2y² from the guided example. Set a=1,b=0,c=−1 to compare its saddle example x²−y².','Bắt đầu với f=x²+xy+2y² trong ví dụ. Đặt a=1,b=0,c=−1 để so sánh ví dụ yên ngựa x²−y².')),
};
