export type Localized = {vi:string;en:string};
export const l = (vi:string,en:string):Localized=>({vi,en});
export const PATH_VERSION='dual-track-1';
export const PLAN_STORAGE='wonder-learning-plan-v1';
export function validDate(value:string):boolean {
 return /^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value+'T12:00:00Z'))&&new Date(value+'T12:00:00Z').toISOString().slice(0,10)===value;
}
/** Dates are a presentation layer. Canonical lesson IDs and saved progress never move. */
export function studyDates(start:string,count:number):string[]{
 if(!validDate(start)||count<0||count>1000)throw Error('Invalid schedule');
 const result:string[]=[];const date=new Date(start+'T12:00:00Z');
 while(result.length<count){if(date.getUTCDay()!==0&&date.getUTCDay()!==6)result.push(date.toISOString().slice(0,10));date.setUTCDate(date.getUTCDate()+1);}
 return result;
}
export function canonicalSessionIndex(date:string){
 if(!validDate(date)||date<'2026-10-07'||date>'2028-10-06')return -1;
 const d=new Date('2026-10-07T12:00:00Z'),end=new Date(date+'T12:00:00Z');let index=-1;
 while(d<=end){if(d.getUTCDay()!==0&&d.getUTCDay()!==6)index++;d.setUTCDate(d.getUTCDate()+1);}
 return index;
}
export function shiftWeekdays(start:string,delta:number){
 if(!validDate(start)||!Number.isInteger(delta)||Math.abs(delta)>523)throw Error('Invalid weekday shift');
 const d=new Date(start+'T12:00:00Z');let left=Math.abs(delta),direction=Math.sign(delta);
 while(left){d.setUTCDate(d.getUTCDate()+direction);if(d.getUTCDay()!==0&&d.getUTCDay()!==6)left--;}
 return d.toISOString().slice(0,10);
}
export type ResearchStage={id:string;start:number;end:number;title:Localized;outcome:Localized;topics:Localized[];artifacts:string[];acceptance:Localized;limit:Localized};
export const researchStages:ResearchStage[]=[
 {id:'P01',start:1,end:20,title:l('Dữ liệu và phép tính tái lập','Reproducible data and numerical work'),outcome:l('Từ CSV thô tới một kết quả chạy lại được bằng một lệnh.','Turn raw CSV into a result that can be rerun with one command.'),
 topics:[l('Git, môi trường Python và một phép tính có test','Git, Python environment and a tested calculation'),l('Đơn vị, phần trăm và lợi suất','Units, percentages and returns'),l('CSV, ngày tháng và dữ liệu thiếu','CSV, dates and missing observations'),l('Bảng dữ liệu, trùng lặp và sắp thứ tự','Tables, duplicates and ordering'),l('Vector hóa và kiểm tra kích thước','Vectorization and shape checks'),l('Phép chiếu bằng QR','Projection using QR'),l('SVD và hạng thiếu','SVD and rank deficiency'),l('Độ điều kiện và nhiễu đầu vào','Conditioning and input perturbation'),l('Fixture phân số độc lập','Independent rational fixtures'),l('Seed và môi trường chạy','Seeds and runtime environments'),l('Đồ thị có trục và đơn vị','Plots with axes and units'),l('Ước lượng trung bình, phương sai','Estimating means and variances'),l('Mô phỏng và sai số Monte Carlo','Simulation and Monte Carlo error'),l('Kiểm thử thuộc tính bất biến','Testing invariants'),l('Chia train/validation/test theo thời gian','Chronological train/validation/test splits'),l('Baseline hằng số','A constant baseline'),l('Đọc một bài báo: câu hỏi và giả thiết','Reading a paper: question and assumptions'),l('Tái tạo một bảng kết quả','Reconstructing a results table'),l('Chạy từ thư mục sạch','Running from a clean directory'),l('Báo cáo sai số và giới hạn','Reporting errors and limitations')],
 artifacts:['README.md','requirements.txt','src/','tests/','data/manifest.json','reports/numerics.md'],acceptance:l('QR/SVD khớp fixture (7/6, 1/2); test ngày trùng/thiếu đơn vị thất bại đúng; chạy lại tạo cùng bảng trong dung sai đã công bố.','QR/SVD matches (7/6, 1/2); duplicate-date/unit tests fail as intended; rerun reproduces tables within declared tolerances.'),limit:l('Chứng minh kỹ năng tính toán cơ bản; chưa phải tín hiệu giao dịch.','Evidence of basic computational work; no trading signal claim.')},
 {id:'P02',start:21,end:44,title:l('Nghiên cứu trên dữ liệu thị trường','Research on market data'),outcome:l('Một backtest theo thời gian với nguồn dữ liệu, baseline và chi phí rõ ràng.','A chronological backtest with documented provenance, baselines and costs.'),
 topics:[l('Nguồn Ken French và quyền sử dụng','Ken French provenance and usage'),l('Chụp phiên bản và SHA-256','Snapshots and SHA-256'),l('Dữ liệu sửa đổi và thay đổi FIZ/CIZ','Revisions and FIZ/CIZ changes'),l('Giá, lợi suất và lợi suất vượt trội','Prices, returns and excess returns'),l('Thông tin có sẵn tại thời điểm quyết định','Information available at decision time'),l('Dịch feature một kỳ','Lagging features by one period'),l('Scaler chỉ fit trên train','Training-only scalers'),l('Ridge một feature','Single-feature ridge'),l('Chọn tham số trên validation','Validation parameter selection'),l('Khoảng cách khi nhãn chồng lấn','Gaps for overlapping labels'),l('Turnover và đơn vị bps','Turnover and basis-point units'),l('Lợi suất ròng sau chi phí','Net returns after costs'),l('Baseline mua và giữ','Buy-and-hold baseline'),l('Drawdown từ đường tài sản','Drawdown from equity curves'),l('Phân phối loss theo thời gian','Loss distributions over time'),l('Bootstrap theo block','Block bootstrap'),l('Null và nhãn tráo ngẫu nhiên','Null models and shuffled labels'),l('Kiểm toán leakage bằng test','Leakage audits using tests'),l('Nhật ký tất cả lần thử','A log of all trials'),l('Đóng băng kế hoạch','Freezing the plan'),l('Mở tập giữ lại một lần','Opening the holdout once'),l('Kiểm tra theo giai đoạn','Subperiod robustness'),l('Kết quả âm và giới hạn dữ liệu','Negative results and data limits'),l('Bản tái lập hoàn chỉnh','Complete reproduction package')],
 artifacts:['data/manifest.json','research-plan.md','trials.csv','src/backtest.py','tests/test_leakage.py','reports/market-study.md'],acceptance:l('Không dùng dữ liệu tương lai; sửa tương lai không đổi dự đoán quá khứ; cost tăng không làm lợi suất ròng tăng khi giữ nguyên vị thế; báo mọi lần thử và tập test đã xem.','No future inputs; future changes leave past predictions unchanged; higher costs cannot improve net returns at fixed positions; disclose every trial and test exposure.'),limit:l('Dữ liệu factor tổng hợp đã được sửa đổi; không chứng minh alpha cổ phiếu point-in-time hay khả năng khớp lệnh.','Revised aggregate factor data do not establish point-in-time stock alpha or executable fills.')},
 {id:'P03',start:45,end:64,title:l('ML alpha: tái lập rồi phản bác','ML alpha: reproduce, then challenge'),outcome:l('So sánh mô hình đơn giản và một mở rộng tự chọn bằng quy trình không nhìn trước.','Compare a simple model and one chosen extension without look-ahead.'),
 topics:[l('Chọn câu hỏi có thể sai','Choose a falsifiable question'),l('Bảng so sánh ba nghiên cứu','Compare three studies'),l('Tái lập baseline công khai','Reproduce a public baseline'),l('Sai số tái lập','Reproduction discrepancies'),l('Giả thuyết mở rộng của bạn','Your extension hypothesis'),l('Feature và thời điểm công bố','Features and release timing'),l('Ridge so với dự đoán hằng','Ridge versus a constant prediction'),l('Một mô hình phi tuyến, có ngân sách tuning','One nonlinear model with a tuning budget'),l('Walk-forward và fit lại','Walk-forward refitting'),l('Loss ghép cặp theo thời gian','Time-paired losses'),l('HAC và bất định phụ thuộc','HAC and dependent uncertainty'),l('Nhiều phép thử và lựa chọn mô hình','Multiple testing and model selection'),l('Ablation một feature','Single-feature ablation'),l('Thay đổi seed và cửa sổ','Seed and window sensitivity'),l('Stress chi phí và turnover','Cost and turnover stress'),l('Thử phản ví dụ mạnh nhất','Test the strongest counterexample'),l('Giữ lại kết quả âm','Retain negative findings'),l('Mở holdout sau khi chốt','Open the holdout after freezing'),l('Viết lập luận có điều kiện','Write a conditional claim'),l('Tự vấn đáp và hồ sơ code','Self-defence and code package')],
 artifacts:['literature.csv','proposal.md','experiments.csv','ablation.csv','report.md','defence.md'],acceptance:l('Tách kết quả tái lập và mở rộng; ghi trước metric, grid, chi phí, split; báo mọi mô hình đã thử; khoảng bất định tính tới phụ thuộc. Không yêu cầu lợi nhuận dương.','Separate reproduction from extension; predefine metrics, grid, costs and splits; report all models tried; account for dependence in uncertainty. Positive profit is not required.'),limit:l('Đây là nghiên cứu tự đánh giá; tính mới và sức thuyết phục chưa được chuyên gia xác nhận.','This is self-assessed research; novelty and persuasiveness remain independently unverified.')},
 {id:'P04',start:65,end:88,title:l('Derivatives: từ không arbitrage tới hedge','Derivatives: from no arbitrage to hedging'),outcome:l('Định giá và kiểm tra call/put châu Âu bằng cây, công thức và Monte Carlo; giải thích sai số hedge.','Price European calls/puts with trees, formulas and Monte Carlo; explain hedge error.'),
 topics:Array.from({length:24},(_,i)=>[l('Brownian và biến phân toàn phương','Brownian motion and quadratic variation'),l('Martingale và thông tin','Martingales and information'),l('Itô và chuyển động Brown hình học','Itô and geometric Brownian motion'),l('Cây nhị phân và xác suất trung hòa rủi ro','Binomial trees and risk-neutral probability'),l('PDE và công thức Black–Scholes','Black–Scholes PDE and formula'),l('Monte Carlo và giảm phương sai','Monte Carlo and variance reduction'),l('Greeks và hedge rời rạc','Greeks and discrete hedging'),l('Implied volatility và rủi ro mô hình','Implied volatility and model risk')][Math.floor(i/3)]),
 artifacts:['src/pricing.py','tests/test_parity.py','convergence.csv','hedge-ledger.csv','reports/model-risk.md'],acceptance:l('Put–call parity, giới hạn T=0/σ=0, hội tụ cây và khoảng MC đúng; SE tính trên cặp antithetic độc lập; sổ tiền mặt hedge cộng lãi và chi phí; phân biệt P và Q.','Check parity, T=0/σ=0 limits, tree convergence and MC intervals; compute SE across independent antithetic pairs; accrue hedge cash and costs; distinguish P and Q.'),limit:l('Chỉ mô hình khuếch tán một tài sản, payoff châu Âu cơ bản. Girsanov tổng quát, volatility surface calibration, American/exotic, rates và HJB chưa được làm chủ.','Single-asset diffusion and basic European payoffs only. General Girsanov, surface calibration, American/exotic options, rates and HJB are not mastered.')},
 {id:'P05',start:89,end:105,title:l('Câu hỏi nghiên cứu của riêng bạn','Your own research question'),outcome:l('Một hồ sơ nghiên cứu ML alpha hoặc derivatives do bạn tự xác định, có thể bị bác bỏ và chạy lại.','A falsifiable, reproducible ML alpha or derivatives study whose question you define.'),
 topics:[l('Đề xuất ba câu hỏi khả thi','Propose three feasible questions'),l('Đối chiếu tài liệu và chọn một câu','Compare literature and choose one'),l('Phạm vi và dữ liệu được phép dùng','Scope and permitted data'),l('Pilot chỉ trên tập phát triển','Pilot on development data only'),l('Tiêu chí bác bỏ và kế hoạch cố định','Falsification criteria and frozen plan'),l('Thực hiện baseline','Implement the baseline'),l('Tái lập kết quả tham chiếu','Reproduce the reference result'),l('Một đóng góp hoặc phản ví dụ','One contribution or counterexample'),l('Kiểm thử code độc lập với triển khai','Tests independent of implementation'),l('Thí nghiệm chính','Primary experiment'),l('Ablation và stress test','Ablations and stress tests'),l('Phân tích độ bất định','Uncertainty analysis'),l('Đánh giá giữ lại','Held-out evaluation'),l('Giải thích thất bại','Explain failures'),l('Báo cáo và giới hạn kết luận','Report and limits of claims'),l('Tự vấn đáp, ghi câu chưa trả lời','Self-defence and unanswered questions'),l('Chạy sạch và công bố GitHub','Clean rerun and GitHub publication')],
 artifacts:['question.md','literature.csv','frozen-plan.json','trials.csv','results/','report.md','defence.md','limitations.md'],acceptance:l('Nêu được câu hỏi không chép đề mẫu; dẫn ba nguồn; có khả năng bác bỏ; manifest + seed + code tái tạo mọi hình; ghi những gì đã xem trước; kết luận chỉ trong phạm vi bằng chứng.','Define a question beyond a supplied exercise; cite three sources; make it falsifiable; reproduce every figure with a manifest, seed and code; disclose prior exposure; bound conclusions by evidence.'),limit:l('Tự vấn đáp và tự chấm không xác nhận nghiên cứu nguyên bản hay năng lực PhD. Không có đánh giá độc lập trong chế độ này.','Self-defence and self-scoring do not establish original research or PhD capability. This mode has no independent evaluation.')},
];
export function researchBlock(week:number,day:number){
 const stage=researchStages.find(s=>week>=s.start&&week<=s.end)!;
 const topic=stage.topics[week-stage.start];
 const phase=[l('Đọc bài hướng dẫn, viết giả thiết và ví dụ tính tay.','Read the guide; write assumptions and a hand calculation.'),l('Cài đặt phiên bản nhỏ nhất; lưu code và đầu vào.','Implement the smallest version; save code and inputs.'),l('Viết test bằng đáp số độc lập và một ca thất bại.','Test against an independent answer and a failure case.'),l('Thay một yếu tố; lưu cả kết quả tốt và xấu.','Change one factor; retain positive and negative results.'),l('Tạo bảng/hình, ghi kết luận và điều chưa biết; commit.','Create a table/figure, record conclusions and unknowns; commit.')][day];
 return {stage,topic,phase,minutes:90};
}
