import {l,type Localized} from './learning-path';
export type PlacementItem={id:string;group:string;prompt:Localized;answer:number;explanation:Localized;critical?:boolean};
const q=(id:string,group:string,vi:string,en:string,answer:number,vex:string,eex:string,critical=false):PlacementItem=>({id,group,prompt:l(vi,en),answer,explanation:l(vex,eex),critical});
export const placementGroups=[
 {id:'algebra',title:l('Số và đại số','Numbers and algebra'),lesson:l('Ứng dụng: đổi lợi suất phần trăm và giải phương trình mô hình. Phân số a/b chỉ có nghĩa khi b khác 0. Quy đồng bằng cách nhân cả tử và mẫu cùng một số; không cộng mẫu. Với ax+b=c, a≠0: trừ b ở hai vế rồi chia a, được x=(c−b)/a. Ví dụ 3x+2=14 ⇒ 3x=12 ⇒ x=4. Tăng 5% nghĩa là nhân 1.05, không cộng 5. Hai kỳ tăng 10% rồi giảm 10% cho 1.1×0.9−1=−0.01, tức −1%.','Application: convert percentage returns and solve model equations. A fraction a/b requires b≠0. Use a common denominator by multiplying numerator and denominator by the same number; never add denominators. For ax+b=c, a≠0, subtract b on both sides then divide by a: x=(c−b)/a. Example: 3x+2=14 gives 3x=12 and x=4. A 5% increase multiplies by 1.05. Up 10% then down 10% gives 1.1×0.9−1=−0.01, or −1%.')},
 {id:'functions',title:l('Hàm số và độ dốc','Functions and slopes'),lesson:l('Ứng dụng: hiểu sensitivity và đồ thị mô hình. Hàm f gán đúng một đầu ra cho mỗi đầu vào trong miền xác định. Với f(x)=x², độ dốc dây cung từ x tới x+h là ((x+h)²−x²)/h=2x+h khi h≠0. Cho h→0 được f′(x)=2x; tại x=3 là 6. Đạo hàm là tốc độ thay đổi cục bộ, không phải giá trị hàm. f(x)=1/(x−2) không xác định tại x=2. Với f(x)=ax+b, độ dốc luôn là a.','Application: interpret sensitivity and model graphs. A function gives exactly one output for each input in its domain. For f(x)=x², the secant slope from x to x+h is ((x+h)²−x²)/h=2x+h for h≠0. Taking h→0 gives f′(x)=2x; at x=3 the slope is 6. A derivative measures local change, not the function value. f(x)=1/(x−2) excludes x=2. For f(x)=ax+b the slope is always a.')},
 {id:'probability',title:l('Xác suất và trung bình','Probability and averages'),lesson:l('Ứng dụng: đọc rủi ro và tránh nhầm xác suất có điều kiện. Nếu các kết quả đồng khả năng, P(A)=số kết quả thuận lợi/tổng số. P(A|B)=P(A∩B)/P(B), chỉ khi P(B)>0. Khi đã biết B, chỉ đếm trong B. Kỳ vọng rời rạc E[X]=ΣxP(X=x). Biến nhận 0 với xác suất 0.75 và 4 với xác suất 0.25 có kỳ vọng 1; kỳ vọng không nhất thiết là kết quả có thể xảy ra. Độc lập cần P(A∩B)=P(A)P(B), không được tự giả sử.','Application: understand risk and avoid conditional-probability mistakes. For equally likely outcomes, P(A)=favourable outcomes/total outcomes. P(A|B)=P(A∩B)/P(B) requires P(B)>0; once B is known, count only within B. For discrete X, E[X]=ΣxP(X=x). A variable equal to 0 with probability .75 and 4 with probability .25 has mean 1; the mean need not be a possible outcome. Independence requires P(A∩B)=P(A)P(B); it cannot be assumed automatically.')},
 {id:'logic',title:l('Vector và lập luận','Vectors and reasoning'),lesson:l('Ứng dụng: kiểm tra kích thước mô hình và phát hiện kết luận quá rộng. Tích vô hướng a·b=Σaᵢbᵢ cần hai vector cùng độ dài. Ma trận m×n nhân vector n×1 cho vector m×1. Để bác bỏ mệnh đề “mọi x đều có P(x)”, chỉ cần một x không có P. Để chứng minh, một ví dụ đúng không đủ. Ví dụ “mọi số nguyên đều chẵn” sai vì 3 không chẵn. Phủ định “mọi” là “tồn tại một trường hợp không”; phủ định “tồn tại” là “mọi trường hợp đều không”.','Application: check model dimensions and detect overgeneralization. The dot product a·b=Σaᵢbᵢ requires vectors of equal length. An m×n matrix times an n×1 vector produces an m×1 vector. One counterexample disproves “for all x, P(x)”; one successful example cannot prove it. “Every integer is even” fails at 3. Negating “for all” gives “there exists a case where not”; negating “there exists” gives “no case satisfies”.')},
];
export function placementItems(form:'A'|'B'):PlacementItem[]{const b=form==='B';return [
 q('a1','algebra',b?'3/4 + 1/8 bằng bao nhiêu? (số thập phân)':'1/2 + 1/4 bằng bao nhiêu? (số thập phân)',b?'Compute 3/4 + 1/8 as a decimal.':'Compute 1/2 + 1/4 as a decimal.',b?.875:.75,b?'6/8+1/8=7/8=0.875.':'2/4+1/4=3/4=0.75.',b?'6/8+1/8=7/8=.875.':'2/4+1/4=3/4=.75.',true),
 q('a2','algebra',b?'5x−3=17. x=?':'3x+2=14. x=?',b?'Solve 5x−3=17.':'Solve 3x+2=14.',4,b?'Cộng 3, chia 5: x=4.':'Trừ 2, chia 3: x=4.',b?'Add 3, divide by 5: x=4.':'Subtract 2, divide by 3: x=4.'),
 q('a3','algebra',b?'80 tăng 25%, giá trị mới?':'200 giảm 10%, giá trị mới?',b?'Increase 80 by 25%.':'Decrease 200 by 10%.',b?100:180,b?'80×1.25=100.':'200×0.9=180.',b?'80×1.25=100.':'200×.9=180.'),
 q('a4','algebra',b?'Tăng 20% rồi giảm 20%: lợi suất tổng (%)?':'Tăng 10% rồi giảm 10%: lợi suất tổng (%)?',b?'Up 20%, then down 20%: total return (%)?':'Up 10%, then down 10%: total return (%)?',b?-4:-1,b?'(1.2×0.8−1)×100=−4.':'(1.1×0.9−1)×100=−1.',b?'(1.2×.8−1)×100=−4.':'(1.1×.9−1)×100=−1.'),
 q('f1','functions',b?'f(x)=2x+1. f(3)=?':'f(x)=x². f(3)=?',b?'f(x)=2x+1. Find f(3).':'f(x)=x². Find f(3).',b?7:9,b?'Thay x=3: 6+1=7.':'3²=9.',b?'Substitute x=3: 6+1=7.':'3²=9.'),
 q('f2','functions',b?'Độ dốc f(x)=5x−2?':'Độ dốc f(x)=3x+2?',b?'Slope of f(x)=5x−2?':'Slope of f(x)=3x+2?',b?5:3,'Hệ số của x là độ dốc.','The coefficient of x is the slope.',true),
 q('f3','functions',b?'Đạo hàm x² tại x=4?':'Đạo hàm x² tại x=3?',b?'Derivative of x² at x=4?':'Derivative of x² at x=3?',b?8:6,'f′(x)=2x, thay điểm đã cho.','f′(x)=2x; substitute the given point.'),
 q('f4','functions',b?'1/(x−5) loại giá trị x nào?':'1/(x−2) loại giá trị x nào?',b?'Which x is excluded for 1/(x−5)?':'Which x is excluded for 1/(x−2)?',b?5:2,'Mẫu bằng 0 thì phép chia không xác định.','Division by zero is undefined.'),
 q('p1','probability',b?'Xúc xắc đều: P(kết quả >4)?':'Xúc xắc đều: P(kết quả chẵn)?',b?'Fair die: P(result >4)?':'Fair die: P(even result)?',b?1/3:.5,b?'Hai kết quả 5,6 trên sáu.':'Ba kết quả 2,4,6 trên sáu.',b?'Two outcomes, 5 and 6, out of six.':'Three outcomes, 2,4,6, out of six.'),
 q('p2','probability',b?'P(A∩B)=0.2, P(B)=0.4. P(A|B)?':'P(A∩B)=0.1, P(B)=0.4. P(A|B)?',b?'P(A∩B)=.2, P(B)=.4. Find P(A|B).':'P(A∩B)=.1, P(B)=.4. Find P(A|B).',b?.5:.25,'Chia xác suất giao cho P(B).','Divide the intersection probability by P(B).',true),
 q('p3','probability',b?'X bằng 0 hoặc 6 với xác suất mỗi giá trị 1/2. E[X]?':'X bằng 0 (p=0.75) hoặc 4 (p=0.25). E[X]?',b?'X is 0 or 6, each with probability 1/2. E[X]?':'X is 0 (p=.75) or 4 (p=.25). E[X]?',b?3:1,'Nhân mỗi giá trị với xác suất rồi cộng.','Multiply each value by its probability and sum.'),
 q('p4','probability',b?'Trung bình của 2,4,9?':'Trung bình của 1,2,6?',b?'Mean of 2,4,9?':'Mean of 1,2,6?',b?5:3,'Cộng ba số rồi chia 3.','Sum the three numbers and divide by 3.'),
 q('l1','logic',b?'(1,3)·(2,4)=?':'(1,2)·(3,4)=?',b?'Compute (1,3)·(2,4).':'Compute (1,2)·(3,4).',b?14:11,'Nhân từng tọa độ tương ứng rồi cộng.','Multiply corresponding coordinates, then sum.'),
 q('l2','logic',b?'Ma trận 4×3 nhân vector 3×1: kết quả có bao nhiêu hàng?':'Ma trận 2×3 nhân vector 3×1: kết quả có bao nhiêu hàng?',b?'A 4×3 matrix times a 3×1 vector: how many output rows?':'A 2×3 matrix times a 3×1 vector: how many output rows?',b?4:2,'Số hàng đầu ra bằng số hàng của ma trận.','The output has as many rows as the matrix.'),
 q('l3','logic',b?'“Mọi x>0 đều có x²≥x”. x=0.25 có bác bỏ không? 1=có, 0=không':'“Mọi x>0 đều có x²≥x”. x=0.5 có bác bỏ không? 1=có, 0=không',b?'Does x=.25 refute “x²≥x for every x>0”? 1=yes, 0=no.':'Does x=.5 refute “x²≥x for every x>0”? 1=yes, 0=no.',1,'Với 0<x<1 thì x²<x. Một phản ví dụ đủ bác bỏ.','For 0<x<1, x²<x. One counterexample is sufficient.',true),
 q('l4','logic',b?'Kiểm tra đúng 200 ví dụ có chứng minh mệnh đề cho mọi số thực không? 1=có, 0=không':'Kiểm tra đúng 100 ví dụ có chứng minh mệnh đề cho mọi số thực không? 1=có, 0=không',b?'Do 200 successful examples prove a claim for all real numbers? 1=yes, 0=no.':'Do 100 successful examples prove a claim for all real numbers? 1=yes, 0=no.',0,'Hữu hạn ví dụ không bao phủ mọi số thực. Cần lập luận tổng quát.','Finitely many examples do not cover every real number. A general argument is required.')
 ];}
export function numericAnswer(raw:string):number|null{const s=raw.trim().replace(',','.');if(!s)return null;const parts=s.split('/');if(parts.length>2||parts.some(p=>!/^[-+]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(p.trim())))return null;const result=parts.length===2?Number(parts[0])/Number(parts[1]):Number(s);return Number.isFinite(result)?result:null;}
export function gradePlacement(form:'A'|'B',answers:Record<string,string>){const items=placementItems(form);return placementGroups.map(group=>{const questions=items.filter(q=>q.group===group.id);const correct=questions.filter(q=>{const n=numericAnswer(answers[q.id]??'');return n!==null&&Math.abs(n-q.answer)<1e-4;});return {...group,score:correct.length,ready:correct.length>=3&&questions.filter(q=>q.critical).every(q=>correct.includes(q))};});}
