import {researchStages} from './learning-path';
const instructions=[
 {vi:`1. Tạo repo Python với thư mục src, tests, data và reports. Ghi phiên bản Python, thư viện và lệnh tái lập trong README. Dùng Python/Git và thư viện mã nguồn mở; không cần cloud trả phí.
2. Tải bộ code khởi đầu ở /research-kit/research.py. Chạy **python research.py --self-test**, rồi **python research.py --out results**. File chỉ dùng thư viện chuẩn. Đọc manifest và CSV trước khi thay mô hình.
3. Viết riêng solver QR hoặc dùng NumPy lstsq; không nghịch đảo AᵀA để giải. Với A=((1,0),(1,1),(1,2)), b=(1,2,2), tính tay β=(7/6,1/2), r=(−1/6,1/3,−1/6). Test Aᵀr=0 bằng phân số hoặc dung sai được giải thích.
4. Cho hai cột gần phụ thuộc, thay ε=10⁻²,10⁻⁴,10⁻⁸ và nhiễu đầu vào cố định. Báo residual và sai số hệ số riêng; residual nhỏ không chứng minh hệ số chính xác.
5. Viết test ngày trùng, số phần trăm bị đọc thành số thập phân, dòng thiếu và seed tái lập. Chạy từ thư mục sạch và tạo lại mọi bảng.`,en:`1. Create a Python repo with src, tests, data and reports. Record Python/library versions and reproduction commands in README. Use Python, Git and open-source libraries; no paid cloud is required.
2. Download /research-kit/research.py. Run **python research.py --self-test**, then **python research.py --out results**. It uses the standard library only. Inspect the manifest and CSV before changing any model.
3. Implement QR or use NumPy lstsq; do not invert AᵀA to solve. For A=((1,0),(1,1),(1,2)), b=(1,2,2), independently calculate β=(7/6,1/2), r=(−1/6,1/3,−1/6). Test Aᵀr=0 using fractions or a justified tolerance.
4. Make two columns nearly dependent, vary ε=10⁻²,10⁻⁴,10⁻⁸ and hold input noise fixed. Report residual and coefficient error separately; a small residual does not prove coefficient accuracy.
5. Test duplicate dates, percent/decimal unit errors, missing rows and reproducible seeds. Rerun from a clean directory and regenerate every table.`},
 {vi:`1. Dùng lab ML alpha để hiểu quy trình, rồi chạy cùng quy tắc trong repo Python. Lưu CSV gốc, SHA-256, nguồn, ngày lấy, khoảng dữ liệu và thay đổi FIZ/CIZ. Chỉ dùng dữ liệu được truy cập miễn phí hợp pháp.
2. Chọn một khoảng lịch sử trước khi nhìn kết quả. Chia 60/20/20 theo thứ tự thời gian. Feature tháng t chỉ dùng dữ liệu trước t; scaler fit trên train. Khi dùng nhãn h kỳ chồng lấn, loại tối thiểu h−1 quan sát có nhãn vượt ranh giới, không random split.
3. Tái lập baseline dự đoán trung bình train và benchmark thị trường. Thử đúng grid L={1,3,12}, λ={0,1,10}; ghi cả 9 kết quả validation, chọn theo MSE đã định trước. Không chọn bằng test.
4. Vị thế long/cash, không leverage. Công thức lợi suất ròng: RF + w(Rm−RF) − c|Δw|. Tính cả vào lệnh và thanh lý, c=bps/10000. So sánh với baseline cùng chi phí. Không gọi factor portfolio là cổ phiếu có thể khớp lệnh.
5. Viết test sửa tương lai không đổi feature/dự đoán quá khứ. Tráo nhãn **chỉ train** bằng seed cố định làm negative control; không biến nó thành chiến lược được chọn. Dùng block bootstrap trên chênh lệch tháng; thử block 3,6,12 và báo nhạy cảm.
6. Chốt metric và mô hình trước khi mở test. Ghi ngày đã xem test. Mọi nghiên cứu tiếp dùng cùng test đều exploratory; không đặt lại nhãn “chưa xem”.`,en:`1. Learn the workflow in the alpha lab, then reproduce its rules in Python. Retain the raw CSV, SHA-256, source, retrieval time, coverage and FIZ/CIZ change. Use legally accessible free data only.
2. Choose a historical interval before seeing results. Split chronologically 60/20/20. A feature at t uses only observations before t; fit scaling on train. For overlapping h-period labels, remove at least h−1 boundary observations whose labels cross the split; never random-split time series.
3. Reproduce a training-mean prediction and the market benchmark. Evaluate exactly L={1,3,12}, λ={0,1,10}; log all nine validation results and choose by predefined MSE. Do not select on test.
4. Use long/cash without leverage. Net return = RF + w(Rm−RF) − c|Δw|; include entry and liquidation, c=bps/10000. Give the benchmark matching costs. Do not describe a factor portfolio as executable stock trades.
5. Test that future edits do not alter past features/predictions. Shuffle **training labels only** with a fixed seed as a negative control, not as a candidate strategy. Block-bootstrap monthly paired differences; report sensitivity to block lengths 3,6,12.
6. Freeze metric and model before opening test. Record the exposure date. Subsequent work using that test is exploratory; do not relabel it unseen.`},
 {vi:`1. Tự chọn một câu hỏi hẹp: một feature có giảm loss ngoài mẫu so với baseline sau chi phí không? Hoặc bất định ước lượng thay đổi thế nào khi tính phụ thuộc? Các ví dụ là gợi ý, không phải câu hỏi bắt buộc hay kết quả kỳ vọng.
2. Lập literature.csv với ba tài liệu toàn văn miễn phí: câu hỏi, dữ liệu, phương pháp, kết quả, giới hạn, điều bạn tái lập và điều bạn thay đổi. Nếu không có dữ liệu/code gốc, ghi “tái tạo phương pháp”, không gọi là tái lập kết quả gốc.
3. Viết proposal trước thí nghiệm: giả thuyết có thể bị bác bỏ, metric chính, split, tối đa số lần tuning, baseline và mức chi phí. Chọn một mở rộng duy nhất so với P02; ví dụ feature phi tuyến hoặc mô hình phi tuyến nhỏ. Không thêm độ phức tạp chỉ để tăng điểm.
4. Giữ cùng các tháng đánh giá để ghép cặp loss. Fit lại trong walk-forward chỉ với quá khứ. Nếu nhãn overlap, purge ranh giới. Báo khoảng sai số có xét phụ thuộc và giới hạn do nhiều thử nghiệm.
5. Ablation bỏ feature chính, negative control và stress chi phí. Lưu cả kết quả âm. Hoàn thành dự án khi quy trình đáng tin và kết luận có điều kiện, kể cả không tìm được alpha.
6. Viết một trang “điều gì làm kết luận sai”. Tự ghi âm hoặc viết vấn đáp 10 phút: tại sao baseline này, nguồn leakage nào còn có thể xảy ra, kết quả có vượt sai số không? Ghi câu chưa trả lời vào hồ sơ.`,en:`1. Choose a narrow question yourself: does one feature reduce held-out loss versus a baseline after costs? Or how does accounting for dependence change uncertainty? These are examples, not prescribed questions or expected findings.
2. Build literature.csv from three free full-text sources: question, data, method, finding, limitation, what you reproduce and what you change. If original data/code are unavailable, label the work a method reconstruction, not a reproduction of the original result.
3. Write a proposal before experimentation: falsifiable hypothesis, primary metric, splits, tuning budget, baseline and costs. Choose just one extension to P02, such as a nonlinear feature or a small nonlinear model. Complexity is not a scoring objective.
4. Compare losses on the same months. Walk-forward refits use past data only. Purge boundaries for overlapping labels. Report dependence-aware uncertainty and limitations from multiple trials.
5. Remove the main feature in an ablation, include a negative control, and stress costs. Keep negative findings. A reliable procedure with bounded conclusions can succeed without finding alpha.
6. Write one page on what would invalidate the conclusion. Record or write a ten-minute self-defence: why this baseline, what leakage could remain, and is the result distinguishable from noise? Retain unanswered questions.`},
 {vi:`1. Học tám chương tại /derivatives theo thứ tự. Mỗi chương ba tuần: dẫn xuất trên giấy, cài đặt, kiểm thử/báo cáo. Lab cung cấp tham chiếu call/put BS, CRR, Monte Carlo và hedge; code của bạn phải có test độc lập với chính thuật toán đó.
2. Fixture: S=K=100,r=.05,σ=.2,T=1 cho call≈10.450584 và delta≈.636831. Kiểm tra parity, T=0, σ=0, đơn điệu theo S và bounds. Không kiểm tra bằng cách sao chép cùng hàm hai lần.
3. Chạy CRR N=25,50,100,200,400; giải thích dao động quanh strike. Từ chối q ngoài [0,1]. Chạy MC nhiều seed và 500,2000,8000 cặp; SE phải dùng trung bình cặp antithetic. Vẽ giá ±1.96SE và giá BS.
4. Cài sổ hedge tự tài trợ với số cổ phiếu, tiền mặt trước/sau lãi, trade, cost và payoff. Bps tính trên notional giao dịch. Dùng cùng đường ngẫu nhiên khi so chi phí; thay N cần ghép gia số Brownian từ lưới mịn để so sánh công bằng.
5. Tự viết bisection implied vol có kiểm tra bounds/bracket/iteration cap. Thử quote sinh từ σ=.1,.2,.5 và quote ngoài bounds. Ghi residual giá, không chỉ σ.
6. Báo cáo rủi ro mô hình: Q khác P, volatility hằng, không cổ tức, không jump, thanh khoản lý tưởng. Không suy ra khả năng định giá exotic/rates hoặc triển khai desk từ bộ kiểm thử này.`,en:`1. Complete the eight /derivatives units in order. Each takes three project weeks: derive, implement, test/report. The lab references BS calls/puts, CRR, Monte Carlo and hedging; your code needs checks independent of those implementations.
2. Fixture: S=K=100,r=.05,σ=.2,T=1 gives call≈10.450584 and delta≈.636831. Check parity, T=0, σ=0, monotonicity in S and bounds. Duplicating the same function is not an independent check.
3. Run CRR N=25,50,100,200,400 and explain strike-alignment oscillations. Reject q outside [0,1]. Run MC across seeds and 500,2000,8000 pairs; estimate SE from antithetic pair means. Plot price ±1.96SE against BS.
4. Implement a self-financing ledger with shares, cash before/after interest, trades, costs and payoff. Bps applies to traded notional. Compare costs on identical random paths; compare grid sizes by aggregating Brownian increments from a fine grid.
5. Implement implied-volatility bisection with bound/bracket checks and an iteration cap. Test quotes generated by σ=.1,.2,.5 and out-of-bound quotes. Report pricing residuals, not only σ.
6. Report model risks: Q versus P, constant volatility, no dividends/jumps and idealized liquidity. These tests do not establish exotic/rates or desk deployment capability.`},
 {vi:`1. Đề xuất ba câu hỏi từ các vấn đề bạn gặp ở P02–P04. Với mỗi câu, viết một điều quan sát được có thể bác bỏ nó và xác nhận dữ liệu/code cần dùng đều miễn phí. Chọn một câu có thể hoàn thành trong ngân sách còn lại; capstone đi sâu **một** nhánh.
2. Đọc tối thiểu ba nguồn toàn văn; phân biệt khoảng trống thật với điều bạn chưa biết. Viết rõ mức đóng góp: tái lập, kiểm tra robustness, phản ví dụ hoặc mở rộng. Chỉ tự tuyên bố tính mới ở mức giả thuyết, chưa được phản biện độc lập.
3. Pilot trên development set; chốt câu hỏi, metric, splits, grid, quy tắc dừng và tiêu chí bác bỏ. Lưu Git commit trước khi chạy thí nghiệm chính. Nếu dùng dữ liệu đã nhìn, ghi exploratory; không thể tạo holdout mới bằng cách quên kết quả.
4. Tạo pipeline một lệnh tái tạo mọi bảng/hình. Lưu environment, seed, SHA-256 và manifest. Thêm test từ phép tính tay/định lý đơn giản, xử lý thiếu dữ liệu, leakage hoặc pricing bounds phù hợp câu hỏi.
5. Chạy thí nghiệm, negative control, ablation và sensitivity. Ghi mọi trial, kể cả thất bại. Dùng uncertainty phù hợp dữ liệu; không yêu cầu p<.05 hay PnL dương để “đỗ”.
6. Viết báo cáo gồm câu hỏi, tài liệu, phương pháp, kết quả, phản bác mạnh nhất, giới hạn và bước tiếp. Tự vấn đáp 15 phút không nhìn lời giải; giữ câu trả lời và phần chưa trả lời. Chạy lại từ môi trường sạch rồi công bố GitHub commit.
7. Kết quả cuối là hồ sơ tự học có bằng chứng. Độ mới, chất lượng chứng minh và khả năng nghề nghiệp vẫn chưa được kiểm chứng độc lập.`,en:`1. Propose three questions arising from P02–P04. For each, state an observable falsifier and confirm all required data/code are free. Choose one feasible within the remaining budget; the capstone goes deep in **one** branch.
2. Read at least three full-text sources; distinguish a genuine literature gap from a gap in your own knowledge. Name the contribution type: reproduction, robustness check, counterexample or extension. Novelty is a self-reported hypothesis until independently reviewed.
3. Pilot only on development data; freeze question, metrics, splits, grid, stopping rules and falsification criteria. Record a Git commit before the main experiment. Previously viewed data remain exploratory; forgetting results does not create a fresh holdout.
4. Build a one-command pipeline for every table/figure. Retain environment, seeds, SHA-256 and manifest. Add independent hand-calculation/theorem fixtures, missing-data handling, leakage or pricing-bound tests appropriate to the question.
5. Run the main experiment, negative control, ablations and sensitivities. Log failed trials too. Use uncertainty suited to the data; neither p<.05 nor positive PnL is a passing requirement.
6. Write question, literature, method, results, strongest rebuttal, limitations and next steps. Conduct a fifteen-minute self-defence without solutions; retain answers and unanswered questions. Rerun in a clean environment and publish a GitHub commit.
7. The output is an evidence-bearing self-study portfolio. Novelty, proof quality and occupational readiness remain independently unverified.`},
];
export const researchProjectGuides=researchStages.map((s,i)=>{
 function body(lang:'vi'|'en'){const vi=lang==='vi';return `${s.outcome[lang]}\n\n## ${vi?'Cách thực hiện':'Implementation'}\n\n${instructions[i][lang]}\n\n## ${vi?'Lịch 90 phút mỗi ngày':'Daily 90-minute schedule'}\n\n${vi?'Mỗi tuần: buổi 1 đọc và tính tay; buổi 2 cài đặt; buổi 3 test; buổi 4 thí nghiệm; buổi 5 viết kết luận và commit. Chưa xong thì tiếp tục, không cộng giờ ngoài 240 phút/ngày.':'Each week: day 1 read and calculate; day 2 implement; day 3 test; day 4 experiment; day 5 report and commit. If unfinished, continue rather than exceeding 240 minutes/day.'}\n\n${s.topics.map((topic,j)=>`- W${s.start+j}: ${topic[lang]}`).join('\n')}\n\n## ${vi?'Sản phẩm trong repo':'Repository artifacts'}\n\n${s.artifacts.map(a=>'- `'+a+'`').join('\n')}\n\n## ${vi?'Tự đánh giá':'Self-assessment'}\n\n${s.acceptance[lang]}\n\n${s.limit[lang]}\n\n[${vi?'Ghi bằng chứng và điều chưa làm được':'Record evidence and remaining gaps'}](/path#evidence) · [${vi?'Mở lab':'Open lab'}](/lab) · [Python starter](/research-kit/research.py)`;}
 return {id:s.id,en:s.title.en,vi:s.title.vi,weeks:`W${String(s.start).padStart(2,'0')}–${s.end}`,enBody:body('en'),viBody:body('vi')};
});
