import type {SceneKind} from '../../lib/concept-scenes';
import type {Bilingual} from '../../lib/lesson-types';
const b=(en:string,vi:string):Bilingual=>({en,vi});
type Figure={kind:SceneKind;title:Bilingual;caption:Bilingual;axes:[string,string];legend:Bilingual[]};
export const conceptFigures:Record<string,Figure>={
 'f-w001-e1':{kind:'secant',title:b('From a secant to a tangent','Từ dây cung đến tiếp tuyến'),caption:b('A stays at x=1. Move B from either side; the secant slope approaches 3. At h=0 the quotient is undefined, so the secant disappears.','A cố định tại x=1. Dịch B từ hai phía; độ dốc dây cung tiến về 3. Tại h=0, thương không xác định nên dây cung được ẩn.'),axes:['x','f(x)'],legend:[b('Function','Hàm số'),b('Tangent at A','Tiếp tuyến tại A'),b('Secant AB','Dây cung AB')]},
 'f-w004-e1':{kind:'cubic',title:b('Derivative of a cubic at −2','Đạo hàm hàm bậc ba tại −2'),caption:b('The tangent slope is positive even though the function value is negative. Approach h=0 from both sides and compare slopes.','Độ dốc tiếp tuyến dương dù giá trị hàm âm. Đưa h về 0 từ hai phía rồi so sánh độ dốc.'),axes:['x','f(x)'],legend:[b('Cubic','Hàm bậc ba'),b('Tangent','Tiếp tuyến'),b('Secant','Dây cung')]},
 'f-w004-e3':{kind:'kink',title:b('Two sides, two slopes','Hai phía, hai độ dốc'),caption:b('Positive h gives slope 1; negative h gives −1. Both points approach the same height, but the slopes disagree. At zero the quotient is undefined.','h dương cho độ dốc 1; h âm cho −1. Hai điểm tiến về cùng độ cao nhưng độ dốc không trùng nhau. Tại 0, thương không xác định.'),axes:['x','|x|'],legend:[b('Absolute value','Trị tuyệt đối'),b('Secant','Dây cung')]},
 'f-w001-e4':{kind:'epsilon',title:b('One threshold for the entire tail','Một ngưỡng cho toàn bộ đuôi dãy'),caption:b('Choose a tolerance. The marked integer N is strictly greater than 2/ε. All subsequent sequence points lie below the dashed line.','Chọn mức sai số. Số nguyên N được đánh dấu lớn hơn nghiêm ngặt 2/ε. Mọi điểm của dãy từ đó trở đi nằm dưới đường nét đứt.'),axes:['n','a_n'],legend:[b('Sequence terms','Các số hạng'),b('Tolerance','Mức sai số')]},
 'f-w014-e2':{kind:'power',title:b('The error hides near the endpoint','Sai số nằm sát đầu mút'),caption:b('The yellow witness moves toward 1 as n grows, but its error remains 1/2. The open circle belongs to the limit graph: the limit is zero before 1 and equals 1 at the endpoint. The supremum error 1 is not attained.','Điểm kiểm tra màu vàng tiến về 1 khi n tăng nhưng sai số luôn là 1/2. Vòng tròn rỗng thuộc đồ thị giới hạn: giới hạn bằng 0 trước điểm 1 và bằng 1 tại đầu mút. Supremum sai số bằng 1 nhưng không đạt được.'),axes:['x','f_n(x),\\ f(x)'],legend:[b('Current function','Hàm hiện tại'),b('Pointwise limit','Giới hạn điểm')]},
 'f-w001-e3':{kind:'bayes',title:b('A positive test depends on the base rate','Dương tính còn phụ thuộc tỷ lệ nền'),caption:b('Sensitivity stays 90% and the false-positive rate stays 5%. Change prevalence p. Counts below are expected counts in a population of 10,000, not a simulated sample.','Giữ độ nhạy 90%, tỷ lệ dương giả 5%. Thay tỷ lệ nền p. Các số đếm bên dưới là số kỳ vọng trong quần thể 10.000, không phải mẫu mô phỏng.'),axes:['p','P(D\\mid+)'],legend:[b('Posterior','Hậu nghiệm'),b('Prior','Tiên nghiệm')]},
 'f-w001-e5':{kind:'binomial',title:b('Where 25 trials put their probability','Phân bố xác suất của 25 lần thử'),caption:b('Each stem is one exact binomial probability. Change the common success probability; the spread collapses at p=0 or p=1. The trials are independent.','Mỗi cột là một xác suất nhị thức chính xác. Thay xác suất thành công chung; độ phân tán mất đi tại p=0 hoặc p=1. Các lần thử độc lập.'),axes:['s','P(S=s)'],legend:[b('Probability mass','Khối xác suất')]},
 'f-w003-e1':{kind:'cauchy',title:b('Equality means the vectors align','Đẳng thức khi hai vector cùng phương'),caption:b('The blue vector stays (1,2); the other is (c,1). At c=1/2 the second is half the first. Compare the absolute dot product with the product of lengths.','Vector xanh cố định (1,2); vector còn lại là (c,1). Tại c=1/2, vector thứ hai bằng nửa vector thứ nhất. So tích vô hướng tuyệt đối với tích độ dài.'),axes:['x_1','x_2'],legend:[b('u=(1,2)','u=(1,2)'),b('v=(c,1)','v=(c,1)')]},
 'm2-w061-e1':{kind:'simplex',title:b('The whole segment stays inside','Toàn bộ đoạn thẳng nằm trong miền'),caption:b('The shaded triangle is the feasible set. Move t from zero to one: the point runs from x to y and always satisfies the three inequalities. This example illustrates the general proof above.','Tam giác tô màu là miền khả thi. Dịch t từ 0 tới 1: điểm đi từ x tới y và luôn thỏa ba bất đẳng thức. Ví dụ này minh họa chứng minh tổng quát bên trên.'),axes:['z_1','z_2'],legend:[b('Segment xy','Đoạn xy')]},
 'm2-w061-e2':{kind:'curvature',title:b('Curvature in two perpendicular directions','Độ cong theo hai hướng vuông góc'),caption:b('At a=2 this is exactly the exercise after completing the square. The two curves are sections through (1,−1), not a 3D surface. Varying a creates related functions: positive means a unique minimum, zero a flat direction, negative a saddle. The Hessian establishes the global conclusion.','Tại a=2, đây chính là bài tập sau khi hoàn thành bình phương. Hai đường là lát cắt qua (1,−1), không phải mặt 3D. Thay a tạo các hàm liên quan: dương cho cực tiểu duy nhất, 0 cho hướng phẳng, âm cho điểm yên ngựa. Hessian xác lập kết luận toàn cục.'),axes:['u','f_a(1+u,-1),\\ f_a(1,-1+u)'],legend:[b('Horizontal section','Lát cắt ngang'),b('Vertical section','Lát cắt dọc')]},
 'm2-w056-e3':{kind:'threshold',title:b('Shrink a coefficient or remove it','Co hệ số hoặc đưa về không'),caption:b('Start at λ=0.5 for the exercise. The three marked inputs are 2.7, 0.4 and −1.2. The central flat segment removes coefficients whose magnitude does not exceed λ.','Bắt đầu tại λ=0.5 đúng như đề. Ba đầu vào được đánh dấu là 2.7, 0.4 và −1.2. Đoạn phẳng ở giữa đưa hệ số có độ lớn không vượt λ về không.'),axes:['z','S_\\lambda(z)'],legend:[b('No shrinkage','Không co'),b('Soft threshold','Ngưỡng mềm')]},
 'm2-w066-e5':{kind:'descent',title:b('A step can converge, oscillate, or explode','Bước đi có thể hội tụ, dao động hoặc phân kỳ'),caption:b('Change η for the exact recurrence in the exercise. At 2 the signs alternate without shrinking. Above 2 the magnitude grows. The vertical scale adjusts to keep all twelve iterates visible.','Thay η trong truy hồi chính xác của đề. Tại 2, dấu luân phiên nhưng độ lớn không giảm. Trên 2, độ lớn tăng. Trục đứng tự điều chỉnh để thấy đủ mười hai bước.'),axes:['k','x_k'],legend:[b('Iterates','Các bước lặp')]},
 'm2-w075-e1':{kind:'spectrum',title:b('A two-tap filter redistributes power','Bộ lọc hai hệ số phân bố lại năng lượng'),caption:b('At θ=0.5, this is the exercise with white-noise variance 4. The horizontal axis is angular frequency in radians. The area is the variance; 2π times the height at zero is the long-run variance.','Tại θ=0.5, đây là bài tập với phương sai nhiễu trắng 4. Trục ngang là tần số góc theo radian. Diện tích là phương sai; 2π lần độ cao tại 0 là phương sai dài hạn.'),axes:['\\omega','f(\\omega)'],legend:[b('Spectral density','Mật độ phổ')]},
 'daily-information-filter':{kind:'gaussian',title:b('Trust the more precise observation','Tin quan sát có độ chính xác cao hơn'),caption:b('Keep the prior N(2,4) and observed value 5 fixed. Vary observation variance R. A small R moves the posterior toward 5 and narrows it. At R=1, mean=4.4 and variance=0.8.','Giữ tiên nghiệm N(2,4) và giá trị quan sát 5. Thay phương sai quan sát R. R nhỏ kéo hậu nghiệm về 5 và làm nó hẹp lại. Tại R=1, trung bình=4.4, phương sai=0.8.'),axes:['x','p(x)'],legend:[b('Prior density','Mật độ tiên nghiệm'),b('Posterior density','Mật độ hậu nghiệm')]},
 'm2-w102-e3':{kind:'risk',title:b('Reported covariance versus actual error','Covariance báo cáo và sai số thực'),caption:b('The true observation noise variance is 4. The wrong gain 1/2 gives MSE 1.25; the optimum 1/5 gives 0.8. Drag the gain and read the excess risk directly.','Phương sai nhiễu quan sát thật là 4. Gain sai 1/2 cho MSE 1.25; gain tối ưu 1/5 cho 0.8. Kéo gain để đọc trực tiếp rủi ro vượt mức.'),axes:['k','\\operatorname{MSE}(k)'],legend:[b('True risk','Rủi ro thực')]},
 'daily-ridge-degrees-freedom':{kind:'ridge',title:b('Regularization removes degrees of freedom gradually','Điều chuẩn giảm dần bậc tự do'),caption:b('The singular values are exactly 3 and 1. Each direction contributes between zero and one. At λ=0 the plotted value is the right-hand limit, rank 2.','Hai singular value đúng bằng 3 và 1. Mỗi hướng đóng góp từ 0 tới 1. Tại λ=0, giá trị vẽ là giới hạn phải, bằng hạng 2.'),axes:['\\lambda','\\operatorname{df}(\\lambda)'],legend:[b('Effective degrees of freedom','Bậc tự do hiệu dụng')]},
 'daily-gaussian-mutual-information':{kind:'information',title:b('Dependence ignores the sign of correlation','Phụ thuộc không phân biệt dấu tương quan'),caption:b('For a jointly Gaussian nonsingular pair, information is symmetric in ρ and is zero at ρ=0. The endpoints ±1 are excluded: the conditional variance vanishes there and information diverges.','Với cặp Gaussian chung không suy biến, thông tin đối xứng theo ρ và bằng 0 tại ρ=0. Loại hai đầu mút ±1: phương sai điều kiện mất đi và thông tin phân kỳ.'),axes:['\\rho','I(X;Y)'],legend:[b('Information in nats','Thông tin theo nat')]},
};
