import type {MathExercise} from '../../lib/math-curriculum-types';
import type {Bilingual} from '../../lib/lesson-types';
const b=(en:string,vi:string):Bilingual=>({en,vi});
function lesson(key:string,title:Bilingual,application:Bilingual,formula:string,steps:Bilingual[],prompt:Bilingual,solution:Bilingual[],error:Bilingual):MathExercise{
 return {id:'daily-'+key,revision:1,title,skills:['derivation','application'],teaching:{application,formula:b(formula,formula),steps},prompt,solution,hints:[],rubric:[{points:4,criterion:b('Derivation and result under the stated assumptions.','Lập luận và kết quả dưới giả thiết đã nêu.')}],commonErrors:[error],remediation:[]};
}
/** Twenty genuinely different mathematical extensions replace repeated primary sessions. */
export const dailyExtensions:Record<string,MathExercise>={
 '72-4':lesson('schur-sensitivity',b('Schur complement and constrained sensitivity','Schur complement và độ nhạy ràng buộc'),
  b('Changing a required exposure changes both the optimal position and its minimum risk.','Thay mức exposure bắt buộc làm đổi cả vị thế tối ưu lẫn rủi ro tối thiểu.'),
  'Q≻0, rank A=m; S=AQ⁻¹Aᵀ≻0; x*(b)=Q⁻¹AᵀS⁻¹b; v(b)=½bᵀS⁻¹b; ∇v(b)=S⁻¹b.',
  [b('Stationarity Qx+Aᵀλ=0 gives x=−Q⁻¹Aᵀλ. Substitution in Ax=b gives −Sλ=b.','Điều kiện dừng Qx+Aᵀλ=0 cho x=−Q⁻¹Aᵀλ. Thay vào Ax=b được −Sλ=b.'),
   b('Full row rank makes Aᵀz nonzero for z≠0, hence zᵀSz=(Aᵀz)ᵀQ⁻¹(Aᵀz)>0.','Hạng hàng đầy đủ khiến Aᵀz khác 0 khi z≠0, nên zᵀSz=(Aᵀz)ᵀQ⁻¹(Aᵀz)>0.'),
   b('Insert x* into ½xᵀQx and differentiate in b. The gradient equals −λ*, with this Lagrangian sign convention.','Thay x* vào ½xᵀQx rồi lấy đạo hàm theo b. Gradient bằng −λ* với quy ước dấu Lagrangian này.')],
  b('Minimize ½(x₁²+4x₂²) subject to x₁+x₂=b. Derive x*(b),v(b),v′(b), then evaluate at b=5.','Tối thiểu ½(x₁²+4x₂²) với x₁+x₂=b. Suy ra x*(b),v(b),v′(b), rồi tính tại b=5.'),
  [b('Q=diag(1,4), A=(1,1); S=5/4 and S⁻¹=4/5.','Q=diag(1,4), A=(1,1); S=5/4 và S⁻¹=4/5.'),
   b('x*=(4b/5,b/5), satisfying feasibility and stationarity. Strict convexity makes it unique.','x*=(4b/5,b/5), thỏa tính khả thi và điều kiện dừng. Lồi nghiêm ngặt cho duy nhất.'),
   b('v=2b²/5, v′=4b/5. At b=5: x*=(4,1),v=10,v′=4.','v=2b²/5, v′=4b/5. Tại b=5: x*=(4,1),v=10,v′=4.')],
  b('Using AAᵀ instead of AQ⁻¹Aᵀ when Q≠I.','Dùng AAᵀ thay AQ⁻¹Aᵀ khi Q≠I.')),
 '84-4':lesson('spectral-coherence',b('Cross-spectrum and coherence','Phổ chéo và coherence'),
  b('Coherence measures dependence at a frequency rather than at a single lag.','Coherence đo phụ thuộc tại một tần số thay vì một độ trễ.'),
  'F(ω)=[[fxx,fxy],[conj(fxy),fyy]]≽0 ⇒ |fxy|²≤fxx fyy; fxx fyy>0 ⇒ C(ω)=|fxy|²/(fxx fyy)∈[0,1].',
  [b('A Hermitian PSD spectral matrix has nonnegative diagonal entries and determinant.','Ma trận phổ Hermitian PSD có đường chéo và định thức không âm.'),
   b('Its determinant is fxx fyy−|fxy|², giving the cross-spectrum bound.','Định thức là fxx fyy−|fxy|², cho cận phổ chéo.'),
   b('Divide by the positive diagonal product. Coherence above one indicates an invalid spectral matrix.','Chia cho tích đường chéo dương. Coherence trên một cho thấy ma trận phổ không hợp lệ.')],
  b('At one frequency fxx=4,fyy=9,fxy=3+3i. Find coherence and check PSD. Repeat with fxy=7.','Tại một tần số fxx=4,fyy=9,fxy=3+3i. Tìm coherence, kiểm PSD. Làm lại với fxy=7.'),
  [b('|3+3i|²=18; coherence=18/36=½.','|3+3i|²=18; coherence=18/36=½.'),
   b('The determinant is 18>0 and diagonals are positive, so the matrix is positive definite.','Định thức 18>0 và đường chéo dương, nên ma trận xác định dương.'),
   b('For fxy=7, determinant=36−49=−13. The matrix is indefinite and cannot be a valid spectral matrix.','Với fxy=7, định thức=36−49=−13. Ma trận bất định, không thể là ma trận phổ hợp lệ.')],
  b('Using the squared real part instead of the squared complex modulus.','Dùng bình phương phần thực thay bình phương môđun phức.')),
 '100-0':lesson('gaussian-mutual-information',b('Gaussian mutual information','Thông tin tương hỗ Gaussian'),
  b('Mutual information measures the reduction of Gaussian uncertainty after an observation.','Thông tin tương hỗ đo mức giảm bất định Gaussian sau một quan sát.'),
  'ΣX≻0, ΣX|Y≻0; I(X;Y)=½log(detΣX/detΣX|Y); |ρ|<1 ⇒ I=−½log(1−ρ²) (nats).',
  [b('For a nonsingular d-dimensional Gaussian, differential entropy is ½log((2πe)^d detΣ).','Với Gaussian d chiều không suy biến, entropy vi phân là ½log((2πe)^d detΣ).'),
   b('Subtract conditional from marginal entropy; the constants cancel. Joint Gaussianity makes conditional covariance independent of the observed value.','Lấy entropy biên trừ entropy điều kiện; hằng số triệt tiêu. Gaussian chung khiến covariance điều kiện không phụ thuộc giá trị quan sát.'),
   b('For scalars, conditional variance is σX²(1−ρ²), so the variance scale cancels.','Với biến vô hướng, phương sai điều kiện là σX²(1−ρ²), nên thang đo phương sai triệt tiêu.')],
  b('For a jointly Gaussian scalar pair with ρ=.6, compute I. Compare ρ=0 and the limit |ρ|→1.','Với cặp Gaussian chung vô hướng có ρ=0,6, tính I. So sánh ρ=0 và giới hạn |ρ|→1.'),
  [b('I=−½log(.64)≈.223144 nats.','I=−½log(0,64)≈0,223144 nat.'),
   b('At ρ=0, joint Gaussianity implies independence and I=0.','Tại ρ=0, Gaussian chung cho độc lập và I=0.'),
   b('As |ρ|→1, conditional variance vanishes and I diverges. The finite-entropy formula excludes the singular endpoint.','Khi |ρ|→1, phương sai điều kiện mất đi và I phân kỳ. Công thức entropy hữu hạn loại điểm biên suy biến.')],
  b('Concluding independence from zero correlation without joint Gaussianity.','Suy độc lập từ tương quan 0 khi thiếu Gaussian chung.')),
 '100-1':lesson('stein-risk',b('Stein’s unbiased risk estimate','Ước lượng rủi ro không chệch Stein'),
  b('SURE estimates squared estimation risk without observing the unknown mean.','SURE ước lượng rủi ro bình phương mà không cần biết trung bình thật.'),
  'Y∼N(θ,σ²I_d); SURE=||g(Y)−Y||²+2σ² div g(Y)−dσ²; E SURE=E||g(Y)−θ||².',
  [b('Assume known σ² and weakly differentiable g with integrable Stein terms. Expand g(Y)−θ=(g(Y)−Y)+(Y−θ).','Giả sử σ² đã biết, g khả vi yếu và các hạng Stein khả tích. Khai triển g(Y)−θ=(g(Y)−Y)+(Y−θ).'),
   b('Gaussian integration by parts gives E[(Yi−θi)gi(Y)]=σ²E[∂igi(Y)], controlling the cross term.','Tích phân từng phần Gaussian cho E[(Yi−θi)gi(Y)]=σ²E[∂igi(Y)], xử lý hạng chéo.'),
   b('Sum over coordinates and use E||Y−θ||²=dσ². Realized SURE may be negative; unbiasedness concerns its expectation.','Cộng theo tọa độ, dùng E||Y−θ||²=dσ². SURE quan sát có thể âm; không chệch nói về kỳ vọng.')],
  b('d=2,σ²=1,g(y)=y/2,y=(2,0). Compute SURE and its expectation for arbitrary θ.','d=2,σ²=1,g(y)=y/2,y=(2,0). Tính SURE và kỳ vọng của nó với θ bất kỳ.'),
  [b('Squared residual=1, divergence=1. SURE=1+2−2=1.','Bình phương residual=1, divergence=1. SURE=1+2−2=1.'),
   b('SURE(Y)=||Y||²/4, so its expectation is (||θ||²+2)/4.','SURE(Y)=||Y||²/4, nên kỳ vọng bằng (||θ||²+2)/4.'),
   b('Direct risk of Y/2 is ||θ||²/4+2/4, which agrees. Realized SURE is not the unknown realized loss.','Rủi ro trực tiếp của Y/2 là ||θ||²/4+2/4, đúng bằng kết quả. SURE quan sát không phải loss thật chưa biết.')],
  b('Equating realized SURE with realized squared error.','Đồng nhất SURE quan sát với sai số bình phương thật.')),
 '100-2':lesson('ridge-degrees-freedom',b('Effective degrees of freedom of ridge','Bậc tự do hiệu dụng của ridge'),
  b('The trace of a smoother measures flexibility after regularization.','Trace của phép làm trơn đo độ linh hoạt sau regularization.'),
  'λ>0; Hλ=X(XᵀX+λI)⁻¹Xᵀ; df(λ)=tr Hλ=Σj sj²/(sj²+λ), sj>0.',
  [b('Use X=USVᵀ. The ridge inverse acts separately on each right singular direction.','Dùng X=USVᵀ. Nghịch đảo ridge tác động riêng lên mỗi hướng singular phải.'),
   b('The fitted-data map has eigenvalues sj²/(sj²+λ) on Col(X), and zero on its orthogonal complement.','Ánh xạ fitted-data có trị riêng sj²/(sj²+λ) trên Col(X), và 0 trên phần trực giao.'),
   b('Trace is their sum. Each decreases in λ, so effective df lies between zero and rank X and need not be integer.','Trace là tổng các trị riêng. Mỗi trị riêng giảm theo λ, nên df hiệu dụng nằm giữa 0 và hạng X, không cần nguyên.')],
  b('Nonzero singular values are 3,1. Find df at λ=1,9 and its limits as λ→0+,∞.','Singular value khác 0 là 3,1. Tìm df tại λ=1,9 và giới hạn khi λ→0+,∞.'),
  [b('df(1)=9/10+1/2=1.4.','df(1)=9/10+1/2=1,4.'),
   b('df(9)=9/18+1/10=.6.','df(9)=9/18+1/10=0,6.'),
   b('Limits are rank X=2 and zero, respectively.','Hai giới hạn lần lượt là hạng X=2 và 0.')],
  b('Always using the parameter count p as effective df.','Luôn dùng số tham số p làm df hiệu dụng.')),
 '100-3':lesson('gaussian-quadratic-mgf',b('MGF of a Gaussian quadratic form','MGF của dạng toàn phương Gaussian'),
  b('Diagonalization gives both a generating function and its exact domain.','Chéo hóa cho cả hàm sinh lẫn miền tồn tại chính xác.'),
  'Z∼N(0,I), A=Aᵀ, I−2tA≻0; E exp(tZᵀAZ)=det(I−2tA)^(-½); E(ZᵀAZ)=tr A; Var(ZᵀAZ)=2tr(A²).',
  [b('Diagonalize A=UΛUᵀ. Orthogonal rotation preserves independent standard normal coordinates.','Chéo hóa A=UΛUᵀ. Quay trực giao giữ các tọa độ chuẩn độc lập.'),
   b('Each scalar Gaussian integral exists only when 1−2tλj>0 and equals (1−2tλj)^(-½).','Mỗi tích phân Gaussian vô hướng chỉ tồn tại khi 1−2tλj>0 và bằng (1−2tλj)^(-½).'),
   b('Multiply factors. Differentiating the log MGF at zero gives trace and twice squared-eigenvalue sum.','Nhân các thừa số. Đạo hàm log MGF tại 0 cho trace và hai lần tổng bình phương trị riêng.')],
  b('A=diag(2,−1). Find the MGF, its exact domain, mean and variance.','A=diag(2,−1). Tìm MGF, miền chính xác, trung bình và phương sai.'),
  [b('MGF=[(1−4t)(1+2t)]^(-½). Both factors must be positive.','MGF=[(1−4t)(1+2t)]^(-½). Cả hai thừa số phải dương.'),
   b('The domain is −½<t<¼; integrals diverge at the endpoints.','Miền là −½<t<¼; tích phân phân kỳ ở hai biên.'),
   b('Mean=1, variance=2(4+1)=10. A is indefinite, so the quadratic form can be negative.','Trung bình=1, phương sai=2(4+1)=10. A bất định nên dạng toàn phương có thể âm.')],
  b('Ignoring negative eigenvalues when finding the MGF domain.','Bỏ qua trị riêng âm khi tìm miền MGF.')),
 '100-4':lesson('multivariate-gaussian-kl',b('KL between Gaussian vectors','KL giữa các vector Gaussian'),
  b('Multivariate KL separates mean and covariance mismatch, including orientation.','KL nhiều chiều tách sai lệch trung bình và covariance, kể cả hướng.'),
  'P=N(m₀,S₀), Q=N(m₁,S₁), S₀,S₁≻0; D(P||Q)=½[tr(S₁⁻¹S₀)+(m₁−m₀)ᵀS₁⁻¹(m₁−m₀)−d+log(det S₁/det S₀)].',
  [b('Subtract Gaussian log densities, keeping both normalization determinants.','Lấy hiệu log mật độ Gaussian, giữ cả hai định thức chuẩn hóa.'),
   b('Under P, E[(X−m1)ᵀS1⁻¹(X−m1)]=tr(S1⁻¹S0)+(m0−m1)ᵀS1⁻¹(m0−m1).','Dưới P, E[(X−m1)ᵀS1⁻¹(X−m1)]=tr(S1⁻¹S0)+(m0−m1)ᵀS1⁻¹(m0−m1).'),
   b('The P-centered term has expectation d. Reversing KL changes both expectation and inverse covariance.','Hạng định tâm theo P có kỳ vọng d. Đảo KL đổi cả phân phối kỳ vọng lẫn nghịch đảo covariance.')],
  b('P=N(0,I₂), Q=N((1,0),diag(2,1)). Compute D(P||Q) and D(Q||P).','P=N(0,I₂), Q=N((1,0),diag(2,1)). Tính D(P||Q), D(Q||P).'),
  [b('Forward trace=1.5, mean term=.5, log ratio=log2, giving ½log2≈.346574.','Trace thuận=1,5, hạng trung bình=0,5, log tỷ số=log2, cho ½log2≈0,346574.'),
   b('Reverse trace=3, mean term=1, log ratio=−log2, giving 1−½log2≈.653426.','Trace ngược=3, hạng trung bình=1, log tỷ số=−log2, cho 1−½log2≈0,653426.'),
   b('Both are nonnegative but unequal; KL is asymmetric.','Cả hai không âm nhưng khác nhau; KL bất đối xứng.')],
  b('Reversing only the determinant ratio in the KL formula.','Chỉ đảo tỷ số định thức trong công thức KL.')),
 '103-0':lesson('split-conformal-rank',b('Split conformal finite-sample ranks','Hạng mẫu hữu hạn của split conformal'),
  b('Held-out exchangeable errors can turn a fixed predictor into an interval with marginal coverage.','Sai số exchangeable giữ lại có thể biến predictor cố định thành khoảng với coverage biên.'),
  'k=ceil((n+1)(1−α)); q=R_(k) if k≤n, q=∞ if k=n+1; P(Rnew≤q)≥1−α.',
  [b('Condition on training data and freeze the predictor before calibration. Calibration and new scores must be exchangeable.','Điều kiện theo dữ liệu huấn luyện, cố định predictor trước calibration. Score calibration và mới phải exchangeable.'),
   b('Without ties, the new score rank among n+1 scores is uniform. The nonrandomized ≤ rule is conservative with ties.','Không có hòa thì hạng score mới trong n+1 score đều. Quy tắc ≤ không ngẫu nhiên bảo thủ khi có hòa.'),
   b('The n+1 correction is essential. A rank beyond n means an infinite threshold, not clipping to the largest calibration score.','Hiệu chỉnh n+1 là thiết yếu. Hạng vượt n nghĩa là ngưỡng vô hạn, không phải cắt về score lớn nhất.')],
  b('Nine calibration residuals are 1,…,9. At α=.2 find q and the interval around prediction 12. Repeat at α=.05.','Chín residual calibration là 1,…,9. Với α=0,2 tìm q và khoảng quanh dự đoán 12. Làm lại với α=0,05.'),
  [b('k=ceil(10·.8)=8, q=8 and interval=[4,20].','k=ceil(10·0,8)=8, q=8 và khoảng=[4,20].'),
   b('At α=.05, k=10, q=∞, so the interval is the whole real line.','Với α=0,05, k=10, q=∞, nên khoảng là toàn trục số.'),
   b('Coverage is marginal over a future exchangeable observation, not conditional at every x and not valid under arbitrary drift.','Coverage là biên theo quan sát tương lai exchangeable, không phải điều kiện tại mọi x và không hợp lệ dưới drift tùy ý.')],
  b('Using ceil(n(1−α)) and calling marginal coverage conditional coverage.','Dùng ceil(n(1−α)) và gọi coverage biên là coverage điều kiện.')),
 '103-1':lesson('finite-population-correction',b('Finite-population correction','Hiệu chỉnh tổng thể hữu hạn'),
  b('Without-replacement sampling reduces variance through negative dependence.','Lấy mẫu không hoàn lại giảm phương sai nhờ phụ thuộc âm.'),
  'N>1; S²=Σi(Yi−Ȳ)²/(N−1); Var(ȳ)=S²(1−n/N)/n, 1≤n≤N.',
  [b('The N population values are fixed; randomness is in a uniformly chosen size-n subset. Each index has inclusion probability n/N.','N giá trị tổng thể cố định; ngẫu nhiên nằm ở tập con n phần tử chọn đều. Mỗi chỉ số có xác suất được chọn n/N.'),
   b('Each sampled position has variance (N−1)S²/N and distinct positions covariance −S²/N.','Mỗi vị trí mẫu có phương sai (N−1)S²/N, hai vị trí khác nhau có covariance −S²/N.'),
   b('Expanding variance of the average yields the finite-population correction; it vanishes at n=N.','Khai triển phương sai trung bình cho hiệu chỉnh tổng thể hữu hạn; phương sai mất đi tại n=N.')],
  b('N=100,S²=25. Find Var(ȳ) for n=20,100. Compare n=20 with sampling with replacement.','N=100,S²=25. Tìm Var(ȳ) với n=20,100. So sánh n=20 với lấy mẫu có hoàn lại.'),
  [b('Without replacement: (25/20)(1−20/100)=1.','Không hoàn lại: (25/20)(1−20/100)=1.'),
   b('At n=100, variance is zero because the sample is the whole population.','Với n=100, phương sai bằng 0 vì mẫu là toàn tổng thể.'),
   b('With replacement, individual variance is 24.75 and mean variance is 24.75/20=1.2375. S² uses denominator N−1, not N.','Có hoàn lại, phương sai mỗi lượt là 24,75, phương sai trung bình là 24,75/20=1,2375. S² dùng mẫu số N−1, không phải N.')],
  b('Using S² as the variance of a uniformly selected population element.','Dùng S² làm phương sai phần tử tổng thể được chọn đều.')),
 '103-2':lesson('tweedie-normal-means',b('Tweedie’s Gaussian denoising formula','Công thức khử nhiễu Gaussian Tweedie'),
  b('The marginal density slope reveals the posterior mean in a normal-means model.','Độ dốc mật độ biên cho biết trung bình hậu nghiệm của mô hình normal-means.'),
  'Y=Θ+ε, ε∼N(0,σ²) independent of Θ; E[Θ|Y=y]=y+σ²∂y log m(y).',
  [b('Write the marginal m as a Gaussian likelihood mixture over the prior. Assume m>0 and differentiation under the integral is valid.','Viết mật độ biên m là hỗn hợp likelihood Gaussian theo prior. Giả sử m>0 và được đổi đạo hàm với tích phân.'),
   b('Differentiate a Gaussian likelihood in y: its derivative is (θ−y)/σ² times the likelihood.','Đạo hàm likelihood Gaussian theo y bằng (θ−y)/σ² nhân likelihood.'),
   b('Dividing the integrated derivative by m gives the posterior expectation of (Θ−y)/σ²; rearrange.','Chia đạo hàm đã tích phân cho m cho kỳ vọng hậu nghiệm của (Θ−y)/σ²; chuyển vế.')],
  b('Θ∼N(0,3), noise variance 1, y=4. Obtain the posterior mean using the marginal density.','Θ∼N(0,3), phương sai nhiễu 1, y=4. Suy trung bình hậu nghiệm từ mật độ biên.'),
  [b('Y∼N(0,4), so log m(y)=constant−y²/8.','Y∼N(0,4), nên log m(y)=hằng số−y²/8.'),
   b('The marginal score is −y/4. Tweedie gives y−y/4=3y/4.','Score biên là −y/4. Tweedie cho y−y/4=3y/4.'),
   b('At y=4, posterior mean=3. A likelihood score at a fixed guessed θ is not the marginal score.','Tại y=4, trung bình hậu nghiệm=3. Score likelihood tại một θ đoán cố định không phải score biên.')],
  b('Using a fixed-θ likelihood score instead of the marginal score.','Dùng score likelihood ở θ cố định thay score biên.')),
 '103-3':lesson('rank-one-information',b('Rank-one information gain','Mức tăng thông tin hạng một'),
  b('One measurement updates information by a rank-one term whose determinant gain is scalar.','Một phép đo cập nhật thông tin bằng hạng một có mức tăng định thức vô hướng.'),
  'J≻0, r>0; J⁺=J+hhᵀ/r; log det J⁺−log det J=log(1+hᵀJ⁻¹h/r).',
  [b('Factor out J using its positive definite square root.','Tách J bằng căn bậc hai xác định dương của nó.'),
   b('The remaining rank-one term has a single nonzero eigenvalue hᵀJ⁻¹h/r, so the identity-plus determinant is one plus that value.','Hạng một còn lại chỉ có một trị riêng khác 0 là hᵀJ⁻¹h/r, nên định thức khi cộng đơn vị bằng một cộng giá trị đó.'),
   b('Take logs. Sensor comparison depends on both measurement direction and noise variance.','Lấy log. So sánh cảm biến phụ thuộc cả hướng đo và phương sai nhiễu.')],
  b('J=diag(1,4), r=1. Compare hA=(1,0),hB=(0,2). What changes if B has r=4?','J=diag(1,4), r=1. So sánh hA=(1,0),hB=(0,2). Nếu B có r=4 thì sao?'),
  [b('J⁻¹=diag(1,¼); both quadratic forms are 1.','J⁻¹=diag(1,¼); cả hai dạng toàn phương bằng 1.'),
   b('At r=1 both gains are log2.','Với r=1, hai mức tăng bằng log2.'),
   b('B at r=4 has normalized quadratic ¼ and gain log(5/4), smaller than log2.','B với r=4 có dạng toàn phương chuẩn hóa ¼ và mức tăng log(5/4), nhỏ hơn log2.')],
  b('Ranking sensors using only ||h|| without noise or J⁻¹.','Xếp hạng cảm biến chỉ bằng ||h|| mà bỏ nhiễu và J⁻¹.')),
 '103-4':lesson('gaussian-score-matching',b('Gaussian scale score matching','Score matching cho thang đo Gaussian'),
  b('Score matching fits log-density derivatives without an observation-dependent normalizer.','Score matching khớp đạo hàm log mật độ mà không cần hằng số chuẩn hóa phụ thuộc quan sát.'),
  'v>0; sv(x)=∂x log N(0,v)=−x/v; J(v)=E[½sv(X)²+∂xsv(X)]=E[X²]/(2v²)−1/v.',
  [b('Under the integration-by-parts boundary conditions, this objective differs from score discrepancy only by a parameter-independent constant.','Dưới điều kiện biên cho tích phân từng phần, mục tiêu này chỉ khác khoảng cách score bởi hằng số không phụ thuộc tham số.'),
   b('For a centered Gaussian model, the data score is −x/v and its x-derivative is −1/v.','Với mô hình Gaussian định tâm, score theo dữ liệu là −x/v, đạo hàm theo x là −1/v.'),
   b('Construct J first, then differentiate in parameter v. If E[X²]>0, the unique minimizer is v=E[X²].','Lập J trước, rồi lấy đạo hàm theo tham số v. Nếu E[X²]>0, nghiệm tối thiểu duy nhất là v=E[X²].')],
  b('Centered data have average squared value 4. Minimize the empirical score-matching objective for v>0; prove the critical point is a minimum.','Dữ liệu định tâm có trung bình bình phương bằng 4. Tối thiểu mục tiêu score-matching thực nghiệm với v>0; chứng minh điểm dừng là cực tiểu.'),
  [b('J=2/v²−1/v, J′=(v−4)/v³.','J=2/v²−1/v, J′=(v−4)/v³.'),
   b('The derivative is negative below 4 and positive above 4, giving a unique global minimum v=4.','Đạo hàm âm dưới 4, dương trên 4, cho cực tiểu toàn cục duy nhất v=4.'),
   b('J(4)=−1/8; negativity is allowed because a parameter-independent constant was omitted.','J(4)=−1/8; mục tiêu âm hợp lệ vì đã bỏ hằng số không phụ thuộc tham số.')],
  b('Confusing ∂x log p with the parameter derivative ∂v log p.','Nhầm ∂x log p với đạo hàm tham số ∂v log p.')),
 '104-0':lesson('discrete-lyapunov',b('Discrete Lyapunov covariance equation','Phương trình covariance Lyapunov rời rạc'),
  b('A stable noisy linear state has a stationary covariance given by a convergent matrix series.','Trạng thái tuyến tính ổn định chịu nhiễu có covariance dừng từ chuỗi ma trận hội tụ.'),
  'ρ(A)<1, Q≽0; P=APAᵀ+Q=Σk≥0 A^k Q(Aᵀ)^k.',
  [b('For independent zero-mean process noise, iterate covariance recurrence: Pm=A^mP0(Aᵀ)^m+Σk=0…m−1 A^kQ(Aᵀ)^k.','Với nhiễu quá trình độc lập trung bình 0, lặp truy hồi covariance: Pm=A^mP0(Aᵀ)^m+Σk=0…m−1 A^kQ(Aᵀ)^k.'),
   b('Spectral radius below one makes powers decay. The initial-state term vanishes and the series converges.','Bán kính phổ dưới một làm lũy thừa suy giảm. Hạng trạng thái đầu mất đi và chuỗi hội tụ.'),
   b('A difference D of two stationary solutions satisfies D=A^mD(Aᵀ)^m for every m, hence D=0.','Hiệu D của hai nghiệm dừng thỏa D=A^mD(Aᵀ)^m với mọi m, nên D=0.')],
  b('Scalar a=½,q=3,P₀=0. Find stationary P and P₂. Why does a=1,q>0 admit no finite stationary P?','Vô hướng a=½,q=3,P₀=0. Tìm P dừng và P₂. Vì sao a=1,q>0 không cho P dừng hữu hạn?'),
  [b('P=P/4+3 gives P=4.','P=P/4+3 cho P=4.'),
   b('P₁=3,P₂=15/4. In general Pm=4(1−4⁻m).','P₁=3,P₂=15/4. Tổng quát Pm=4(1−4⁻m).'),
   b('At a=1 the equation is P=P+q, impossible for finite P when q>0.','Tại a=1 phương trình là P=P+q, vô nghiệm P hữu hạn khi q>0.')],
  b('Assuming entries of A smaller than one guarantee ρ(A)<1.','Cho rằng từng phần tử A nhỏ hơn một bảo đảm ρ(A)<1.')),
 '104-1':lesson('information-filter',b('Information-form observation update','Cập nhật quan sát dạng thông tin'),
  b('Independent Gaussian measurements add precision rather than covariance.','Phép đo Gaussian độc lập cộng precision, không cộng covariance.'),
  'J=P⁻¹, h=Jm; J⁺=J+HᵀR⁻¹H; h⁺=h+HᵀR⁻¹y; P⁺=(J⁺)⁻¹; m⁺=P⁺h⁺.',
  [b('Assume x~N(m,P), P≻0, and y=Hx+ε with independent Gaussian noise R≻0. Write the prior log density as −½xᵀJx+xᵀh plus a constant.','Giả sử x~N(m,P), P≻0, y=Hx+ε với nhiễu Gaussian độc lập R≻0. Viết log prior là −½xᵀJx+xᵀh cộng hằng số.'),
   b('Expand observation log likelihood; its quadratic and linear terms add HᵀR⁻¹H and HᵀR⁻¹y.','Khai triển log likelihood quan sát; hạng bậc hai và tuyến tính cộng HᵀR⁻¹H và HᵀR⁻¹y.'),
   b('Complete the square to recover posterior mean and covariance. Correlated sensors need a joint R, not independent updates.','Hoàn thành bình phương để lấy trung bình và covariance hậu nghiệm. Cảm biến tương quan cần R chung, không cập nhật độc lập.')],
  b('Prior N(2,4), H=1, y=5 and noise variance 1. Find the posterior in information form.','Prior N(2,4), H=1, y=5, phương sai nhiễu 1. Tìm hậu nghiệm dạng thông tin.'),
  [b('J=¼,h=½.','J=¼,h=½.'),
   b('J⁺=5/4,h⁺=11/2.','J⁺=5/4,h⁺=11/2.'),
   b('Posterior variance=4/5, mean=(4/5)(11/2)=4.4, closer to the more precise observation.','Phương sai hậu nghiệm=4/5, trung bình=(4/5)(11/2)=4,4, gần quan sát có precision lớn hơn.')],
  b('Adding measurement variance to prior precision.','Cộng phương sai đo vào precision prior.')),
 '104-2':lesson('missing-observation',b('Filtering a missing observation','Lọc khi thiếu một quan sát'),
  b('A missing noninformative reading gives no likelihood and must not be replaced by an invented zero.','Quan sát thiếu không cung cấp thông tin thì không có likelihood và không được thay bằng số 0 bịa ra.'),
  'm⁻=Am, P⁻=APAᵀ+Q; noninformative missing observation ⇒ m⁺=m⁻, P⁺=P⁻.',
  [b('Propagate the state through its transition model before checking observation availability.','Lan truyền trạng thái qua mô hình chuyển trước khi kiểm tra có quan sát hay không.'),
   b('If missingness is independent of the state, the absence likelihood is constant and does not update the predicted distribution.','Nếu thiếu độc lập với trạng thái, likelihood của sự vắng mặt là hằng và không cập nhật phân phối dự đoán.'),
   b('State-dependent missingness can be informative; the skip-update rule then needs a justified missingness model.','Việc thiếu phụ thuộc trạng thái có thể có thông tin; khi đó quy tắc bỏ cập nhật cần mô hình thiếu có căn cứ.')],
  b('A=1,Q=2,previous m=3,P=1. Find m,P after one and two missing readings independent of the state. Compare a fabricated y=0,R=1 at the first step.','A=1,Q=2,m trước=3,P=1. Tìm m,P sau một và hai quan sát thiếu độc lập với trạng thái. So với giả y=0,R=1 tại bước đầu.'),
  [b('One missing reading: m=3,P=3. Two: m=3,P=5.','Một lần thiếu: m=3,P=3. Hai lần: m=3,P=5.'),
   b('A fictitious zero has gain 3/4 and yields m=¾,P=¾.','Quan sát 0 giả có gain 3/4, cho m=¾,P=¾.'),
   b('The reduced uncertainty is fabricated. Under the valid random-walk model, absence of readings does not stop noise accumulation.','Bất định giảm là giả tạo. Dưới mô hình random walk đúng, thiếu quan sát không ngăn nhiễu tích lũy.')],
  b('Replacing a missing reading with zero and treating it as observed.','Thay quan sát thiếu bằng 0 rồi coi là đã quan sát.')),
 '104-3':lesson('backward-simulation',b('Backward conditional simulation','Mô phỏng điều kiện ngược'),
  b('Conditioning a past state on a sampled future state permits posterior trajectory simulation.','Điều kiện trạng thái quá khứ theo trạng thái tương lai đã lấy mẫu cho mô phỏng quỹ đạo hậu nghiệm.'),
  'Pnext⁻=APtAᵀ+Q≻0; B=PtAᵀ(Pnext⁻)⁻¹; xt|xt+1,y1:t ∼ N(mt+B(xt+1−Amt), Pt−B Pnext⁻ Bᵀ).',
  [b('The filtered joint covariance of (xt,xt+1) has cross block PtAᵀ under independent transition noise.','Covariance chung đã lọc của (xt,xt+1) có khối chéo PtAᵀ dưới nhiễu chuyển độc lập.'),
   b('Gaussian block conditioning yields the backward conditional law. Its covariance is independent of the sampled future value.','Điều kiện hóa Gaussian theo khối cho phân phối điều kiện ngược. Covariance không phụ thuộc giá trị tương lai đã lấy mẫu.'),
   b('Sample xT from its filtered law, then sample backwards recursively. The Markov model makes future observations redundant once xt+1 is given.','Lấy xT từ phân phối đã lọc, rồi lấy mẫu ngược. Mô hình Markov khiến quan sát tương lai không bổ sung khi đã cho xt+1.')],
  b('mt=2,Pt=3,A=1,Q=1 and sampled xt+1=6. Find the backward mean and variance.','mt=2,Pt=3,A=1,Q=1, trạng thái tương lai đã lấy mẫu xt+1=6. Tìm trung bình và phương sai ngược.'),
  [b('Pnext⁻=4, B=3/4.','Pnext⁻=4, B=3/4.'),
   b('Mean=2+(3/4)(6−2)=5.','Trung bình=2+(3/4)(6−2)=5.'),
   b('Variance=3−(3/4)²4=3/4. Draw from N(5,3/4); using only 5 discards trajectory uncertainty.','Phương sai=3−(3/4)²4=3/4. Lấy từ N(5,3/4); chỉ dùng 5 làm mất bất định quỹ đạo.')],
  b('Treating the conditional mean as a random trajectory draw.','Coi trung bình điều kiện là quỹ đạo ngẫu nhiên đã lấy mẫu.')),
 '104-4':lesson('correlated-sensor-fusion',b('Optimal correlated-sensor fusion','Hợp nhất tối ưu cảm biến tương quan'),
  b('Correlated errors change averaging weights and can make a negative weight optimal.','Sai số tương quan đổi trọng số trung bình, có thể làm trọng số âm tối ưu.'),
  'Var(e1)=a, Var(e2)=b, Cov(e1,e2)=c; Var(we1+(1−w)e2)=w²a+(1−w)²b+2w(1−w)c; a+b−2c>0 ⇒ w*=(b−c)/(a+b−2c).',
  [b('Assume unbiased readings and a PSD covariance matrix. Weights summing to one preserve unbiasedness.','Giả sử phép đo không chệch, ma trận covariance PSD. Tổng trọng số bằng một giữ không chệch.'),
   b('Differentiate the variance quadratic. Its curvature is 2Var(e1−e2)=2(a+b−2c)>0.','Lấy đạo hàm phương sai bậc hai. Độ cong là 2Var(e1−e2)=2(a+b−2c)>0.'),
   b('The formula optimizes over real w. If w∈[0,1] is required, clip the optimum to that interval.','Công thức tối ưu trên w thực. Nếu yêu cầu w∈[0,1], cắt nghiệm tối ưu vào khoảng này.')],
  b('a=1,b=4,c=1.5. Check validity, find optimal real w and variance, then impose 0≤w≤1.','a=1,b=4,c=1,5. Kiểm tính hợp lệ, tìm w thực tối ưu và phương sai, rồi thêm 0≤w≤1.'),
  [b('ab−c²=1.75>0 and a,b>0, so covariance is positive definite.','ab−c²=1,75>0, a,b>0 nên covariance xác định dương.'),
   b('w*=2.5/2=1.25 and minimum variance=(ab−c²)/(a+b−2c)=.875.','w*=2,5/2=1,25, phương sai tối thiểu=(ab−c²)/(a+b−2c)=0,875.'),
   b('With [0,1] weights, w=1 is optimal and variance=1. The unconstrained solution gave sensor two weight −.25.','Với trọng số [0,1], w=1 tối ưu, phương sai=1. Nghiệm không ràng buộc cho cảm biến hai trọng số −0,25.')],
  b('Omitting the covariance term in the variance of the weighted average.','Bỏ hạng covariance trong phương sai trung bình trọng số.')),
 '105-0':lesson('posterior-predictive-mixture',b('Posterior predictive uncertainty','Bất định dự báo hậu nghiệm'),
  b('Forecast uncertainty includes both observation noise and uncertainty about the mean.','Bất định dự báo gồm nhiễu quan sát lẫn bất định về trung bình.'),
  'Θ|D∼N(m,V), ε∼N(0,σ²) independent given D; Ynew=Θ+ε ⇒ Ynew|D∼N(m,V+σ²).',
  [b('Given Θ, the new observation has mean Θ and variance σ².','Cho Θ, quan sát mới có trung bình Θ và phương sai σ².'),
   b('Total variance is E[Var(Ynew|Θ,D)|D]+Var(E[Ynew|Θ,D]|D)=σ²+V.','Phương sai toàn phần là E[Var(Ynew|Θ,D)|D]+Var(E[Ynew|Θ,D]|D)=σ²+V.'),
   b('The sum of conditionally independent normals is normal. Plugging in only m omits V.','Tổng các Gaussian độc lập có điều kiện là Gaussian. Chỉ thay m làm mất V.')],
  b('Θ|D∼N(2,3), new noise variance 1. Find predictive distribution and central 95% interval using 1.96; compare plug-in.','Θ|D∼N(2,3), phương sai nhiễu mới 1. Tìm phân phối dự báo, khoảng trung tâm 95% dùng 1,96; so plug-in.'),
  [b('Predictive N(2,4), standard deviation 2.','Dự báo N(2,4), độ lệch chuẩn 2.'),
   b('Interval=2±1.96·2=[−1.92,5.92].','Khoảng=2±1,96·2=[−1,92;5,92].'),
   b('Plug-in N(2,1) gives [.04,3.96] and ignores mean uncertainty. These intervals are model-based, not distribution-free coverage guarantees.','Plug-in N(2,1) cho [0,04;3,96], bỏ bất định trung bình. Các khoảng theo mô hình, không phải bảo đảm coverage distribution-free.')],
  b('Calling an interval for Θ an interval for a new noisy observation.','Gọi khoảng cho Θ là khoảng cho quan sát mới có nhiễu.')),
 '105-1':lesson('e-value-mixtures',b('Combining dependent e-values','Gộp e-value phụ thuộc'),
  b('Fixed averaging combines evidence from dependent analyses under a common null.','Trung bình cố định gộp bằng chứng từ phân tích phụ thuộc dưới một null chung.'),
  'Ei≥0, E₀Ei≤1; wi≥0 fixed, Σwi=1 ⇒ E=ΣwiEi≥0, E₀E≤1; P₀(E≥1/α)≤α.',
  [b('Linearity of expectation bounds the weighted average without independence. All component claims must hold under the same null.','Tuyến tính kỳ vọng chặn trung bình trọng số mà không cần độc lập. Mọi kết luận thành phần phải đúng dưới cùng null.'),
   b('Markov’s inequality on the nonnegative average gives the 1/α rejection threshold.','Markov cho trung bình không âm tạo ngưỡng bác bỏ 1/α.'),
   b('Data-selected weights are not fixed weights. Products need additional dependence conditions and are not licensed by this averaging proof.','Trọng số chọn theo dữ liệu không cố định. Tích cần điều kiện phụ thuộc bổ sung, không được bảo đảm bởi chứng minh trung bình.')],
  b('Observed E1=40,E2=2 with equal fixed weights: does the mixture cross the α=.05 threshold? Give dependent e-values whose product is invalid.','Quan sát E1=40,E2=2 với trọng số cố định bằng nhau: hỗn hợp vượt ngưỡng α=0,05 không? Cho e-value phụ thuộc có tích không hợp lệ.'),
  [b('The average is 21, exceeding threshold 20. This is a testing rule, not a posterior probability.','Trung bình là 21, vượt ngưỡng 20. Đây là quy tắc kiểm định, không phải xác suất hậu nghiệm.'),
   b('Let E1=E2=2 with probability ½ under the null, otherwise both zero. Each has expectation one.','Cho E1=E2=2 với xác suất ½ dưới null, còn lại cả hai 0. Mỗi kỳ vọng bằng một.'),
   b('Their product has expectation 4·½=2>1, so it is not an e-value.','Tích có kỳ vọng 4·½=2>1, nên không phải e-value.')],
  b('Assuming a product of arbitrarily dependent e-values is valid.','Cho rằng tích e-value phụ thuộc tùy ý là hợp lệ.')),
 '105-2':lesson('prequential-bayes-factor',b('Prequential model evidence','Bằng chứng mô hình qua dự báo tuần tự'),
  b('Marginal likelihood factors into one-step predictive densities, linking forecasting and model comparison.','Marginal likelihood phân tích thành mật độ dự báo một bước, nối dự báo với so sánh mô hình.'),
  'pM(y1:T)=Πt pM(yt|y<t); log BFA,B=Σt[log pA(yt|y<t)−log pB(yt|y<t)]; posterior odds=prior odds×BF.',
  [b('Apply the probability chain rule; each prediction conditions only on the past. Predictive densities must be positive for these finite log ratios.','Áp dụng quy tắc chuỗi xác suất; mỗi dự báo chỉ điều kiện theo quá khứ. Mật độ dự báo phải dương để tỷ số log hữu hạn.'),
   b('Take a model ratio and logarithm. Differences add without requiring observations to be independent.','Lấy tỷ số mô hình rồi log. Hiệu cộng được mà không cần các quan sát độc lập.'),
   b('Convert updated odds to probability only after including prior odds. Forecasts and priors must be specified before the corresponding outcomes.','Chỉ chuyển odds cập nhật thành xác suất sau khi gồm odds prior. Dự báo và prior phải định trước kết quả tương ứng.')],
  b('A gives predictive densities (.4,.5,.2), B gives (.2,.25,.4). Compute BF and posterior P(A|data) for prior P(A)=⅓ with only models A,B.','A cho mật độ dự báo (0,4;0,5;0,2), B cho (0,2;0,25;0,4). Tính BF và P(A|data) khi prior P(A)=⅓, chỉ có A,B.'),
  [b('Predictive ratios are 2,2,½, so BF=2 and log BF=log2.','Tỷ số dự báo là 2,2,½ nên BF=2, log BF=log2.'),
   b('Prior odds are ½; posterior odds are ½·2=1.','Odds prior là ½; odds hậu nghiệm là ½·2=1.'),
   b('Posterior probability is 1/(1+1)=½. BF/(1+BF)=⅔ would incorrectly assume equal prior odds.','Xác suất hậu nghiệm là 1/(1+1)=½. BF/(1+BF)=⅔ giả sử sai odds prior bằng nhau.')],
  b('Converting a Bayes factor to a probability without prior odds.','Chuyển Bayes factor thành xác suất mà bỏ odds prior.')),
};
